//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.SerSinhvien {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTSinhvien", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTSinhvien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSinhVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSinhVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoDemField;
        
        private bool GioiTinhField;
        
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLopHanhChinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLopHanhChinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AnhDaiDienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaSinhVien {
            get {
                return this.MaSinhVienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSinhVienField, value) != true)) {
                    this.MaSinhVienField = value;
                    this.RaisePropertyChanged("MaSinhVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenSinhVien {
            get {
                return this.TenSinhVienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSinhVienField, value) != true)) {
                    this.TenSinhVienField = value;
                    this.RaisePropertyChanged("TenSinhVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HoDem {
            get {
                return this.HoDemField;
            }
            set {
                if ((object.ReferenceEquals(this.HoDemField, value) != true)) {
                    this.HoDemField = value;
                    this.RaisePropertyChanged("HoDem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((this.GioiTinhField.Equals(value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MaLopHanhChinh {
            get {
                return this.MaLopHanhChinhField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLopHanhChinhField, value) != true)) {
                    this.MaLopHanhChinhField = value;
                    this.RaisePropertyChanged("MaLopHanhChinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TenLopHanhChinh {
            get {
                return this.TenLopHanhChinhField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLopHanhChinhField, value) != true)) {
                    this.TenLopHanhChinhField = value;
                    this.RaisePropertyChanged("TenLopHanhChinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] AnhDaiDien {
            get {
                return this.AnhDaiDienField;
            }
            set {
                if ((object.ReferenceEquals(this.AnhDaiDienField, value) != true)) {
                    this.AnhDaiDienField = value;
                    this.RaisePropertyChanged("AnhDaiDien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTLophanhchinh", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTLophanhchinh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLopHanhChinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLopHanhChinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaGiangVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenGiangVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        private int NamNhapHocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaLopHanhChinh {
            get {
                return this.MaLopHanhChinhField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLopHanhChinhField, value) != true)) {
                    this.MaLopHanhChinhField = value;
                    this.RaisePropertyChanged("MaLopHanhChinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenLopHanhChinh {
            get {
                return this.TenLopHanhChinhField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLopHanhChinhField, value) != true)) {
                    this.TenLopHanhChinhField = value;
                    this.RaisePropertyChanged("TenLopHanhChinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MaGiangVien {
            get {
                return this.MaGiangVienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaGiangVienField, value) != true)) {
                    this.MaGiangVienField = value;
                    this.RaisePropertyChanged("MaGiangVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TenGiangVien {
            get {
                return this.TenGiangVienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenGiangVienField, value) != true)) {
                    this.TenGiangVienField = value;
                    this.RaisePropertyChanged("TenGiangVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int NamNhapHoc {
            get {
                return this.NamNhapHocField;
            }
            set {
                if ((this.NamNhapHocField.Equals(value) != true)) {
                    this.NamNhapHocField = value;
                    this.RaisePropertyChanged("NamNhapHoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SerSinhvien.SerSinhvienSoap")]
    public interface SerSinhvienSoap {
        
        // CODEGEN: Generating message contract since element name GetAllSinhVienResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSinhVien", ReplyAction="*")]
        Presentation.SerSinhvien.GetAllSinhVienResponse GetAllSinhVien(Presentation.SerSinhvien.GetAllSinhVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSinhVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetAllSinhVienResponse> GetAllSinhVienAsync(Presentation.SerSinhvien.GetAllSinhVienRequest request);
        
        // CODEGEN: Generating message contract since element name magv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSinhVienLHC", ReplyAction="*")]
        Presentation.SerSinhvien.GetSinhVienLHCResponse GetSinhVienLHC(Presentation.SerSinhvien.GetSinhVienLHCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSinhVienLHC", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetSinhVienLHCResponse> GetSinhVienLHCAsync(Presentation.SerSinhvien.GetSinhVienLHCRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllLopHCResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLopHC", ReplyAction="*")]
        Presentation.SerSinhvien.GetAllLopHCResponse GetAllLopHC(Presentation.SerSinhvien.GetAllLopHCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLopHC", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetAllLopHCResponse> GetAllLopHCAsync(Presentation.SerSinhvien.GetAllLopHCRequest request);
        
        // CODEGEN: Generating message contract since element name lop from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SortSinhVien", ReplyAction="*")]
        Presentation.SerSinhvien.SortSinhVienResponse SortSinhVien(Presentation.SerSinhvien.SortSinhVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SortSinhVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.SortSinhVienResponse> SortSinhVienAsync(Presentation.SerSinhvien.SortSinhVienRequest request);
        
        // CODEGEN: Generating message contract since element name sea from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchSinhVien", ReplyAction="*")]
        Presentation.SerSinhvien.SearchSinhVienResponse SearchSinhVien(Presentation.SerSinhvien.SearchSinhVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchSinhVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.SearchSinhVienResponse> SearchSinhVienAsync(Presentation.SerSinhvien.SearchSinhVienRequest request);
        
        // CODEGEN: Generating message contract since element name mas from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAnhSinhVien", ReplyAction="*")]
        Presentation.SerSinhvien.GetAnhSinhVienResponse GetAnhSinhVien(Presentation.SerSinhvien.GetAnhSinhVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAnhSinhVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetAnhSinhVienResponse> GetAnhSinhVienAsync(Presentation.SerSinhvien.GetAnhSinhVienRequest request);
        
        // CODEGEN: Generating message contract since element name GetTinhThanhResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTinhThanh", ReplyAction="*")]
        Presentation.SerSinhvien.GetTinhThanhResponse GetTinhThanh(Presentation.SerSinhvien.GetTinhThanhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTinhThanh", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetTinhThanhResponse> GetTinhThanhAsync(Presentation.SerSinhvien.GetTinhThanhRequest request);
        
        // CODEGEN: Generating message contract since element name maTinh from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHuyen", ReplyAction="*")]
        Presentation.SerSinhvien.GetHuyenResponse GetHuyen(Presentation.SerSinhvien.GetHuyenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHuyen", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetHuyenResponse> GetHuyenAsync(Presentation.SerSinhvien.GetHuyenRequest request);
        
        // CODEGEN: Generating message contract since element name maHuyen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXa", ReplyAction="*")]
        Presentation.SerSinhvien.GetXaResponse GetXa(Presentation.SerSinhvien.GetXaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXa", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetXaResponse> GetXaAsync(Presentation.SerSinhvien.GetXaRequest request);
        
        // CODEGEN: Generating message contract since element name sinhVien from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemSinhVien", ReplyAction="*")]
        Presentation.SerSinhvien.ThemSinhVienResponse ThemSinhVien(Presentation.SerSinhvien.ThemSinhVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemSinhVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.ThemSinhVienResponse> ThemSinhVienAsync(Presentation.SerSinhvien.ThemSinhVienRequest request);
        
        // CODEGEN: Generating message contract since element name sinhVien from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditSinhVien", ReplyAction="*")]
        Presentation.SerSinhvien.EditSinhVienResponse EditSinhVien(Presentation.SerSinhvien.EditSinhVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditSinhVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.EditSinhVienResponse> EditSinhVienAsync(Presentation.SerSinhvien.EditSinhVienRequest request);
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSinhVien", ReplyAction="*")]
        Presentation.SerSinhvien.DeleteSinhVienResponse DeleteSinhVien(Presentation.SerSinhvien.DeleteSinhVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSinhVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.DeleteSinhVienResponse> DeleteSinhVienAsync(Presentation.SerSinhvien.DeleteSinhVienRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSinhVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSinhVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetAllSinhVienRequestBody Body;
        
        public GetAllSinhVienRequest() {
        }
        
        public GetAllSinhVienRequest(Presentation.SerSinhvien.GetAllSinhVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSinhVienRequestBody {
        
        public GetAllSinhVienRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSinhVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSinhVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetAllSinhVienResponseBody Body;
        
        public GetAllSinhVienResponse() {
        }
        
        public GetAllSinhVienResponse(Presentation.SerSinhvien.GetAllSinhVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSinhVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerSinhvien.DTSinhvien[] GetAllSinhVienResult;
        
        public GetAllSinhVienResponseBody() {
        }
        
        public GetAllSinhVienResponseBody(Presentation.SerSinhvien.DTSinhvien[] GetAllSinhVienResult) {
            this.GetAllSinhVienResult = GetAllSinhVienResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSinhVienLHCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSinhVienLHC", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetSinhVienLHCRequestBody Body;
        
        public GetSinhVienLHCRequest() {
        }
        
        public GetSinhVienLHCRequest(Presentation.SerSinhvien.GetSinhVienLHCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSinhVienLHCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string magv;
        
        public GetSinhVienLHCRequestBody() {
        }
        
        public GetSinhVienLHCRequestBody(string magv) {
            this.magv = magv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSinhVienLHCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSinhVienLHCResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetSinhVienLHCResponseBody Body;
        
        public GetSinhVienLHCResponse() {
        }
        
        public GetSinhVienLHCResponse(Presentation.SerSinhvien.GetSinhVienLHCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSinhVienLHCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerSinhvien.DTSinhvien[] GetSinhVienLHCResult;
        
        public GetSinhVienLHCResponseBody() {
        }
        
        public GetSinhVienLHCResponseBody(Presentation.SerSinhvien.DTSinhvien[] GetSinhVienLHCResult) {
            this.GetSinhVienLHCResult = GetSinhVienLHCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllLopHCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllLopHC", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetAllLopHCRequestBody Body;
        
        public GetAllLopHCRequest() {
        }
        
        public GetAllLopHCRequest(Presentation.SerSinhvien.GetAllLopHCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllLopHCRequestBody {
        
        public GetAllLopHCRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllLopHCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllLopHCResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetAllLopHCResponseBody Body;
        
        public GetAllLopHCResponse() {
        }
        
        public GetAllLopHCResponse(Presentation.SerSinhvien.GetAllLopHCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllLopHCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerSinhvien.DTLophanhchinh[] GetAllLopHCResult;
        
        public GetAllLopHCResponseBody() {
        }
        
        public GetAllLopHCResponseBody(Presentation.SerSinhvien.DTLophanhchinh[] GetAllLopHCResult) {
            this.GetAllLopHCResult = GetAllLopHCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SortSinhVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SortSinhVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.SortSinhVienRequestBody Body;
        
        public SortSinhVienRequest() {
        }
        
        public SortSinhVienRequest(Presentation.SerSinhvien.SortSinhVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SortSinhVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lop;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string gio;
        
        public SortSinhVienRequestBody() {
        }
        
        public SortSinhVienRequestBody(string lop, string dia, string gio) {
            this.lop = lop;
            this.dia = dia;
            this.gio = gio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SortSinhVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SortSinhVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.SortSinhVienResponseBody Body;
        
        public SortSinhVienResponse() {
        }
        
        public SortSinhVienResponse(Presentation.SerSinhvien.SortSinhVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SortSinhVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerSinhvien.DTSinhvien[] SortSinhVienResult;
        
        public SortSinhVienResponseBody() {
        }
        
        public SortSinhVienResponseBody(Presentation.SerSinhvien.DTSinhvien[] SortSinhVienResult) {
            this.SortSinhVienResult = SortSinhVienResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchSinhVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchSinhVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.SearchSinhVienRequestBody Body;
        
        public SearchSinhVienRequest() {
        }
        
        public SearchSinhVienRequest(Presentation.SerSinhvien.SearchSinhVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchSinhVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sea;
        
        public SearchSinhVienRequestBody() {
        }
        
        public SearchSinhVienRequestBody(string sea) {
            this.sea = sea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchSinhVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchSinhVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.SearchSinhVienResponseBody Body;
        
        public SearchSinhVienResponse() {
        }
        
        public SearchSinhVienResponse(Presentation.SerSinhvien.SearchSinhVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchSinhVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerSinhvien.DTSinhvien[] SearchSinhVienResult;
        
        public SearchSinhVienResponseBody() {
        }
        
        public SearchSinhVienResponseBody(Presentation.SerSinhvien.DTSinhvien[] SearchSinhVienResult) {
            this.SearchSinhVienResult = SearchSinhVienResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnhSinhVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnhSinhVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetAnhSinhVienRequestBody Body;
        
        public GetAnhSinhVienRequest() {
        }
        
        public GetAnhSinhVienRequest(Presentation.SerSinhvien.GetAnhSinhVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnhSinhVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mas;
        
        public GetAnhSinhVienRequestBody() {
        }
        
        public GetAnhSinhVienRequestBody(string mas) {
            this.mas = mas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnhSinhVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnhSinhVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetAnhSinhVienResponseBody Body;
        
        public GetAnhSinhVienResponse() {
        }
        
        public GetAnhSinhVienResponse(Presentation.SerSinhvien.GetAnhSinhVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnhSinhVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetAnhSinhVienResult;
        
        public GetAnhSinhVienResponseBody() {
        }
        
        public GetAnhSinhVienResponseBody(byte[] GetAnhSinhVienResult) {
            this.GetAnhSinhVienResult = GetAnhSinhVienResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTinhThanhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTinhThanh", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetTinhThanhRequestBody Body;
        
        public GetTinhThanhRequest() {
        }
        
        public GetTinhThanhRequest(Presentation.SerSinhvien.GetTinhThanhRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTinhThanhRequestBody {
        
        public GetTinhThanhRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTinhThanhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTinhThanhResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetTinhThanhResponseBody Body;
        
        public GetTinhThanhResponse() {
        }
        
        public GetTinhThanhResponse(Presentation.SerSinhvien.GetTinhThanhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTinhThanhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerSinhvien.ArrayOfString[] GetTinhThanhResult;
        
        public GetTinhThanhResponseBody() {
        }
        
        public GetTinhThanhResponseBody(Presentation.SerSinhvien.ArrayOfString[] GetTinhThanhResult) {
            this.GetTinhThanhResult = GetTinhThanhResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHuyenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHuyen", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetHuyenRequestBody Body;
        
        public GetHuyenRequest() {
        }
        
        public GetHuyenRequest(Presentation.SerSinhvien.GetHuyenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHuyenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string maTinh;
        
        public GetHuyenRequestBody() {
        }
        
        public GetHuyenRequestBody(string maTinh) {
            this.maTinh = maTinh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHuyenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHuyenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetHuyenResponseBody Body;
        
        public GetHuyenResponse() {
        }
        
        public GetHuyenResponse(Presentation.SerSinhvien.GetHuyenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHuyenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerSinhvien.ArrayOfString[] GetHuyenResult;
        
        public GetHuyenResponseBody() {
        }
        
        public GetHuyenResponseBody(Presentation.SerSinhvien.ArrayOfString[] GetHuyenResult) {
            this.GetHuyenResult = GetHuyenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXa", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetXaRequestBody Body;
        
        public GetXaRequest() {
        }
        
        public GetXaRequest(Presentation.SerSinhvien.GetXaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string maHuyen;
        
        public GetXaRequestBody() {
        }
        
        public GetXaRequestBody(string maHuyen) {
            this.maHuyen = maHuyen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.GetXaResponseBody Body;
        
        public GetXaResponse() {
        }
        
        public GetXaResponse(Presentation.SerSinhvien.GetXaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerSinhvien.ArrayOfString[] GetXaResult;
        
        public GetXaResponseBody() {
        }
        
        public GetXaResponseBody(Presentation.SerSinhvien.ArrayOfString[] GetXaResult) {
            this.GetXaResult = GetXaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ThemSinhVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ThemSinhVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.ThemSinhVienRequestBody Body;
        
        public ThemSinhVienRequest() {
        }
        
        public ThemSinhVienRequest(Presentation.SerSinhvien.ThemSinhVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ThemSinhVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerSinhvien.DTSinhvien sinhVien;
        
        public ThemSinhVienRequestBody() {
        }
        
        public ThemSinhVienRequestBody(Presentation.SerSinhvien.DTSinhvien sinhVien) {
            this.sinhVien = sinhVien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ThemSinhVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ThemSinhVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.ThemSinhVienResponseBody Body;
        
        public ThemSinhVienResponse() {
        }
        
        public ThemSinhVienResponse(Presentation.SerSinhvien.ThemSinhVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ThemSinhVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ThemSinhVienResult;
        
        public ThemSinhVienResponseBody() {
        }
        
        public ThemSinhVienResponseBody(bool ThemSinhVienResult) {
            this.ThemSinhVienResult = ThemSinhVienResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditSinhVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditSinhVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.EditSinhVienRequestBody Body;
        
        public EditSinhVienRequest() {
        }
        
        public EditSinhVienRequest(Presentation.SerSinhvien.EditSinhVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditSinhVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerSinhvien.DTSinhvien sinhVien;
        
        public EditSinhVienRequestBody() {
        }
        
        public EditSinhVienRequestBody(Presentation.SerSinhvien.DTSinhvien sinhVien) {
            this.sinhVien = sinhVien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditSinhVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditSinhVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.EditSinhVienResponseBody Body;
        
        public EditSinhVienResponse() {
        }
        
        public EditSinhVienResponse(Presentation.SerSinhvien.EditSinhVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditSinhVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditSinhVienResult;
        
        public EditSinhVienResponseBody() {
        }
        
        public EditSinhVienResponseBody(bool EditSinhVienResult) {
            this.EditSinhVienResult = EditSinhVienResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSinhVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSinhVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.DeleteSinhVienRequestBody Body;
        
        public DeleteSinhVienRequest() {
        }
        
        public DeleteSinhVienRequest(Presentation.SerSinhvien.DeleteSinhVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSinhVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        public DeleteSinhVienRequestBody() {
        }
        
        public DeleteSinhVienRequestBody(string ma) {
            this.ma = ma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSinhVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSinhVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerSinhvien.DeleteSinhVienResponseBody Body;
        
        public DeleteSinhVienResponse() {
        }
        
        public DeleteSinhVienResponse(Presentation.SerSinhvien.DeleteSinhVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSinhVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteSinhVienResult;
        
        public DeleteSinhVienResponseBody() {
        }
        
        public DeleteSinhVienResponseBody(bool DeleteSinhVienResult) {
            this.DeleteSinhVienResult = DeleteSinhVienResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SerSinhvienSoapChannel : Presentation.SerSinhvien.SerSinhvienSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerSinhvienSoapClient : System.ServiceModel.ClientBase<Presentation.SerSinhvien.SerSinhvienSoap>, Presentation.SerSinhvien.SerSinhvienSoap {
        
        public SerSinhvienSoapClient() {
        }
        
        public SerSinhvienSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerSinhvienSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerSinhvienSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerSinhvienSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.GetAllSinhVienResponse Presentation.SerSinhvien.SerSinhvienSoap.GetAllSinhVien(Presentation.SerSinhvien.GetAllSinhVienRequest request) {
            return base.Channel.GetAllSinhVien(request);
        }
        
        public Presentation.SerSinhvien.DTSinhvien[] GetAllSinhVien() {
            Presentation.SerSinhvien.GetAllSinhVienRequest inValue = new Presentation.SerSinhvien.GetAllSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.GetAllSinhVienRequestBody();
            Presentation.SerSinhvien.GetAllSinhVienResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetAllSinhVien(inValue);
            return retVal.Body.GetAllSinhVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetAllSinhVienResponse> Presentation.SerSinhvien.SerSinhvienSoap.GetAllSinhVienAsync(Presentation.SerSinhvien.GetAllSinhVienRequest request) {
            return base.Channel.GetAllSinhVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.GetAllSinhVienResponse> GetAllSinhVienAsync() {
            Presentation.SerSinhvien.GetAllSinhVienRequest inValue = new Presentation.SerSinhvien.GetAllSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.GetAllSinhVienRequestBody();
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetAllSinhVienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.GetSinhVienLHCResponse Presentation.SerSinhvien.SerSinhvienSoap.GetSinhVienLHC(Presentation.SerSinhvien.GetSinhVienLHCRequest request) {
            return base.Channel.GetSinhVienLHC(request);
        }
        
        public Presentation.SerSinhvien.DTSinhvien[] GetSinhVienLHC(string magv) {
            Presentation.SerSinhvien.GetSinhVienLHCRequest inValue = new Presentation.SerSinhvien.GetSinhVienLHCRequest();
            inValue.Body = new Presentation.SerSinhvien.GetSinhVienLHCRequestBody();
            inValue.Body.magv = magv;
            Presentation.SerSinhvien.GetSinhVienLHCResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetSinhVienLHC(inValue);
            return retVal.Body.GetSinhVienLHCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetSinhVienLHCResponse> Presentation.SerSinhvien.SerSinhvienSoap.GetSinhVienLHCAsync(Presentation.SerSinhvien.GetSinhVienLHCRequest request) {
            return base.Channel.GetSinhVienLHCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.GetSinhVienLHCResponse> GetSinhVienLHCAsync(string magv) {
            Presentation.SerSinhvien.GetSinhVienLHCRequest inValue = new Presentation.SerSinhvien.GetSinhVienLHCRequest();
            inValue.Body = new Presentation.SerSinhvien.GetSinhVienLHCRequestBody();
            inValue.Body.magv = magv;
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetSinhVienLHCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.GetAllLopHCResponse Presentation.SerSinhvien.SerSinhvienSoap.GetAllLopHC(Presentation.SerSinhvien.GetAllLopHCRequest request) {
            return base.Channel.GetAllLopHC(request);
        }
        
        public Presentation.SerSinhvien.DTLophanhchinh[] GetAllLopHC() {
            Presentation.SerSinhvien.GetAllLopHCRequest inValue = new Presentation.SerSinhvien.GetAllLopHCRequest();
            inValue.Body = new Presentation.SerSinhvien.GetAllLopHCRequestBody();
            Presentation.SerSinhvien.GetAllLopHCResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetAllLopHC(inValue);
            return retVal.Body.GetAllLopHCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetAllLopHCResponse> Presentation.SerSinhvien.SerSinhvienSoap.GetAllLopHCAsync(Presentation.SerSinhvien.GetAllLopHCRequest request) {
            return base.Channel.GetAllLopHCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.GetAllLopHCResponse> GetAllLopHCAsync() {
            Presentation.SerSinhvien.GetAllLopHCRequest inValue = new Presentation.SerSinhvien.GetAllLopHCRequest();
            inValue.Body = new Presentation.SerSinhvien.GetAllLopHCRequestBody();
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetAllLopHCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.SortSinhVienResponse Presentation.SerSinhvien.SerSinhvienSoap.SortSinhVien(Presentation.SerSinhvien.SortSinhVienRequest request) {
            return base.Channel.SortSinhVien(request);
        }
        
        public Presentation.SerSinhvien.DTSinhvien[] SortSinhVien(string lop, string dia, string gio) {
            Presentation.SerSinhvien.SortSinhVienRequest inValue = new Presentation.SerSinhvien.SortSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.SortSinhVienRequestBody();
            inValue.Body.lop = lop;
            inValue.Body.dia = dia;
            inValue.Body.gio = gio;
            Presentation.SerSinhvien.SortSinhVienResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).SortSinhVien(inValue);
            return retVal.Body.SortSinhVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.SortSinhVienResponse> Presentation.SerSinhvien.SerSinhvienSoap.SortSinhVienAsync(Presentation.SerSinhvien.SortSinhVienRequest request) {
            return base.Channel.SortSinhVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.SortSinhVienResponse> SortSinhVienAsync(string lop, string dia, string gio) {
            Presentation.SerSinhvien.SortSinhVienRequest inValue = new Presentation.SerSinhvien.SortSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.SortSinhVienRequestBody();
            inValue.Body.lop = lop;
            inValue.Body.dia = dia;
            inValue.Body.gio = gio;
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).SortSinhVienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.SearchSinhVienResponse Presentation.SerSinhvien.SerSinhvienSoap.SearchSinhVien(Presentation.SerSinhvien.SearchSinhVienRequest request) {
            return base.Channel.SearchSinhVien(request);
        }
        
        public Presentation.SerSinhvien.DTSinhvien[] SearchSinhVien(string sea) {
            Presentation.SerSinhvien.SearchSinhVienRequest inValue = new Presentation.SerSinhvien.SearchSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.SearchSinhVienRequestBody();
            inValue.Body.sea = sea;
            Presentation.SerSinhvien.SearchSinhVienResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).SearchSinhVien(inValue);
            return retVal.Body.SearchSinhVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.SearchSinhVienResponse> Presentation.SerSinhvien.SerSinhvienSoap.SearchSinhVienAsync(Presentation.SerSinhvien.SearchSinhVienRequest request) {
            return base.Channel.SearchSinhVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.SearchSinhVienResponse> SearchSinhVienAsync(string sea) {
            Presentation.SerSinhvien.SearchSinhVienRequest inValue = new Presentation.SerSinhvien.SearchSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.SearchSinhVienRequestBody();
            inValue.Body.sea = sea;
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).SearchSinhVienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.GetAnhSinhVienResponse Presentation.SerSinhvien.SerSinhvienSoap.GetAnhSinhVien(Presentation.SerSinhvien.GetAnhSinhVienRequest request) {
            return base.Channel.GetAnhSinhVien(request);
        }
        
        public byte[] GetAnhSinhVien(string mas) {
            Presentation.SerSinhvien.GetAnhSinhVienRequest inValue = new Presentation.SerSinhvien.GetAnhSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.GetAnhSinhVienRequestBody();
            inValue.Body.mas = mas;
            Presentation.SerSinhvien.GetAnhSinhVienResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetAnhSinhVien(inValue);
            return retVal.Body.GetAnhSinhVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetAnhSinhVienResponse> Presentation.SerSinhvien.SerSinhvienSoap.GetAnhSinhVienAsync(Presentation.SerSinhvien.GetAnhSinhVienRequest request) {
            return base.Channel.GetAnhSinhVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.GetAnhSinhVienResponse> GetAnhSinhVienAsync(string mas) {
            Presentation.SerSinhvien.GetAnhSinhVienRequest inValue = new Presentation.SerSinhvien.GetAnhSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.GetAnhSinhVienRequestBody();
            inValue.Body.mas = mas;
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetAnhSinhVienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.GetTinhThanhResponse Presentation.SerSinhvien.SerSinhvienSoap.GetTinhThanh(Presentation.SerSinhvien.GetTinhThanhRequest request) {
            return base.Channel.GetTinhThanh(request);
        }
        
        public Presentation.SerSinhvien.ArrayOfString[] GetTinhThanh() {
            Presentation.SerSinhvien.GetTinhThanhRequest inValue = new Presentation.SerSinhvien.GetTinhThanhRequest();
            inValue.Body = new Presentation.SerSinhvien.GetTinhThanhRequestBody();
            Presentation.SerSinhvien.GetTinhThanhResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetTinhThanh(inValue);
            return retVal.Body.GetTinhThanhResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetTinhThanhResponse> Presentation.SerSinhvien.SerSinhvienSoap.GetTinhThanhAsync(Presentation.SerSinhvien.GetTinhThanhRequest request) {
            return base.Channel.GetTinhThanhAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.GetTinhThanhResponse> GetTinhThanhAsync() {
            Presentation.SerSinhvien.GetTinhThanhRequest inValue = new Presentation.SerSinhvien.GetTinhThanhRequest();
            inValue.Body = new Presentation.SerSinhvien.GetTinhThanhRequestBody();
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetTinhThanhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.GetHuyenResponse Presentation.SerSinhvien.SerSinhvienSoap.GetHuyen(Presentation.SerSinhvien.GetHuyenRequest request) {
            return base.Channel.GetHuyen(request);
        }
        
        public Presentation.SerSinhvien.ArrayOfString[] GetHuyen(string maTinh) {
            Presentation.SerSinhvien.GetHuyenRequest inValue = new Presentation.SerSinhvien.GetHuyenRequest();
            inValue.Body = new Presentation.SerSinhvien.GetHuyenRequestBody();
            inValue.Body.maTinh = maTinh;
            Presentation.SerSinhvien.GetHuyenResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetHuyen(inValue);
            return retVal.Body.GetHuyenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetHuyenResponse> Presentation.SerSinhvien.SerSinhvienSoap.GetHuyenAsync(Presentation.SerSinhvien.GetHuyenRequest request) {
            return base.Channel.GetHuyenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.GetHuyenResponse> GetHuyenAsync(string maTinh) {
            Presentation.SerSinhvien.GetHuyenRequest inValue = new Presentation.SerSinhvien.GetHuyenRequest();
            inValue.Body = new Presentation.SerSinhvien.GetHuyenRequestBody();
            inValue.Body.maTinh = maTinh;
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetHuyenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.GetXaResponse Presentation.SerSinhvien.SerSinhvienSoap.GetXa(Presentation.SerSinhvien.GetXaRequest request) {
            return base.Channel.GetXa(request);
        }
        
        public Presentation.SerSinhvien.ArrayOfString[] GetXa(string maHuyen) {
            Presentation.SerSinhvien.GetXaRequest inValue = new Presentation.SerSinhvien.GetXaRequest();
            inValue.Body = new Presentation.SerSinhvien.GetXaRequestBody();
            inValue.Body.maHuyen = maHuyen;
            Presentation.SerSinhvien.GetXaResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetXa(inValue);
            return retVal.Body.GetXaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.GetXaResponse> Presentation.SerSinhvien.SerSinhvienSoap.GetXaAsync(Presentation.SerSinhvien.GetXaRequest request) {
            return base.Channel.GetXaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.GetXaResponse> GetXaAsync(string maHuyen) {
            Presentation.SerSinhvien.GetXaRequest inValue = new Presentation.SerSinhvien.GetXaRequest();
            inValue.Body = new Presentation.SerSinhvien.GetXaRequestBody();
            inValue.Body.maHuyen = maHuyen;
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).GetXaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.ThemSinhVienResponse Presentation.SerSinhvien.SerSinhvienSoap.ThemSinhVien(Presentation.SerSinhvien.ThemSinhVienRequest request) {
            return base.Channel.ThemSinhVien(request);
        }
        
        public bool ThemSinhVien(Presentation.SerSinhvien.DTSinhvien sinhVien) {
            Presentation.SerSinhvien.ThemSinhVienRequest inValue = new Presentation.SerSinhvien.ThemSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.ThemSinhVienRequestBody();
            inValue.Body.sinhVien = sinhVien;
            Presentation.SerSinhvien.ThemSinhVienResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).ThemSinhVien(inValue);
            return retVal.Body.ThemSinhVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.ThemSinhVienResponse> Presentation.SerSinhvien.SerSinhvienSoap.ThemSinhVienAsync(Presentation.SerSinhvien.ThemSinhVienRequest request) {
            return base.Channel.ThemSinhVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.ThemSinhVienResponse> ThemSinhVienAsync(Presentation.SerSinhvien.DTSinhvien sinhVien) {
            Presentation.SerSinhvien.ThemSinhVienRequest inValue = new Presentation.SerSinhvien.ThemSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.ThemSinhVienRequestBody();
            inValue.Body.sinhVien = sinhVien;
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).ThemSinhVienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.EditSinhVienResponse Presentation.SerSinhvien.SerSinhvienSoap.EditSinhVien(Presentation.SerSinhvien.EditSinhVienRequest request) {
            return base.Channel.EditSinhVien(request);
        }
        
        public bool EditSinhVien(Presentation.SerSinhvien.DTSinhvien sinhVien) {
            Presentation.SerSinhvien.EditSinhVienRequest inValue = new Presentation.SerSinhvien.EditSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.EditSinhVienRequestBody();
            inValue.Body.sinhVien = sinhVien;
            Presentation.SerSinhvien.EditSinhVienResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).EditSinhVien(inValue);
            return retVal.Body.EditSinhVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.EditSinhVienResponse> Presentation.SerSinhvien.SerSinhvienSoap.EditSinhVienAsync(Presentation.SerSinhvien.EditSinhVienRequest request) {
            return base.Channel.EditSinhVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.EditSinhVienResponse> EditSinhVienAsync(Presentation.SerSinhvien.DTSinhvien sinhVien) {
            Presentation.SerSinhvien.EditSinhVienRequest inValue = new Presentation.SerSinhvien.EditSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.EditSinhVienRequestBody();
            inValue.Body.sinhVien = sinhVien;
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).EditSinhVienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerSinhvien.DeleteSinhVienResponse Presentation.SerSinhvien.SerSinhvienSoap.DeleteSinhVien(Presentation.SerSinhvien.DeleteSinhVienRequest request) {
            return base.Channel.DeleteSinhVien(request);
        }
        
        public bool DeleteSinhVien(string ma) {
            Presentation.SerSinhvien.DeleteSinhVienRequest inValue = new Presentation.SerSinhvien.DeleteSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.DeleteSinhVienRequestBody();
            inValue.Body.ma = ma;
            Presentation.SerSinhvien.DeleteSinhVienResponse retVal = ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).DeleteSinhVien(inValue);
            return retVal.Body.DeleteSinhVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerSinhvien.DeleteSinhVienResponse> Presentation.SerSinhvien.SerSinhvienSoap.DeleteSinhVienAsync(Presentation.SerSinhvien.DeleteSinhVienRequest request) {
            return base.Channel.DeleteSinhVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerSinhvien.DeleteSinhVienResponse> DeleteSinhVienAsync(string ma) {
            Presentation.SerSinhvien.DeleteSinhVienRequest inValue = new Presentation.SerSinhvien.DeleteSinhVienRequest();
            inValue.Body = new Presentation.SerSinhvien.DeleteSinhVienRequestBody();
            inValue.Body.ma = ma;
            return ((Presentation.SerSinhvien.SerSinhvienSoap)(this)).DeleteSinhVienAsync(inValue);
        }
    }
}
