//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.SerTaikhoan {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTTaikhoan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTTaikhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        private int PasswordField;
        
        private byte RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((this.PasswordField.Equals(value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public byte Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SerTaikhoan.SerTaikhoanSoap")]
    public interface SerTaikhoanSoap {
        
        // CODEGEN: Generating message contract since element name taiKhoan from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Presentation.SerTaikhoan.LoginResponse Login(Presentation.SerTaikhoan.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerTaikhoan.LoginResponse> LoginAsync(Presentation.SerTaikhoan.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name taiKhoan from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePass", ReplyAction="*")]
        Presentation.SerTaikhoan.ChangePassResponse ChangePass(Presentation.SerTaikhoan.ChangePassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePass", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerTaikhoan.ChangePassResponse> ChangePassAsync(Presentation.SerTaikhoan.ChangePassRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerTaikhoan.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Presentation.SerTaikhoan.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerTaikhoan.DTTaikhoan taiKhoan;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(Presentation.SerTaikhoan.DTTaikhoan taiKhoan) {
            this.taiKhoan = taiKhoan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerTaikhoan.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Presentation.SerTaikhoan.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerTaikhoan.DTTaikhoan LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(Presentation.SerTaikhoan.DTTaikhoan LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePass", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerTaikhoan.ChangePassRequestBody Body;
        
        public ChangePassRequest() {
        }
        
        public ChangePassRequest(Presentation.SerTaikhoan.ChangePassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerTaikhoan.DTTaikhoan taiKhoan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int oldp;
        
        public ChangePassRequestBody() {
        }
        
        public ChangePassRequestBody(Presentation.SerTaikhoan.DTTaikhoan taiKhoan, int oldp) {
            this.taiKhoan = taiKhoan;
            this.oldp = oldp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerTaikhoan.ChangePassResponseBody Body;
        
        public ChangePassResponse() {
        }
        
        public ChangePassResponse(Presentation.SerTaikhoan.ChangePassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePassResult;
        
        public ChangePassResponseBody() {
        }
        
        public ChangePassResponseBody(bool ChangePassResult) {
            this.ChangePassResult = ChangePassResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SerTaikhoanSoapChannel : Presentation.SerTaikhoan.SerTaikhoanSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerTaikhoanSoapClient : System.ServiceModel.ClientBase<Presentation.SerTaikhoan.SerTaikhoanSoap>, Presentation.SerTaikhoan.SerTaikhoanSoap {
        
        public SerTaikhoanSoapClient() {
        }
        
        public SerTaikhoanSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerTaikhoanSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerTaikhoanSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerTaikhoanSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerTaikhoan.LoginResponse Presentation.SerTaikhoan.SerTaikhoanSoap.Login(Presentation.SerTaikhoan.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public Presentation.SerTaikhoan.DTTaikhoan Login(Presentation.SerTaikhoan.DTTaikhoan taiKhoan) {
            Presentation.SerTaikhoan.LoginRequest inValue = new Presentation.SerTaikhoan.LoginRequest();
            inValue.Body = new Presentation.SerTaikhoan.LoginRequestBody();
            inValue.Body.taiKhoan = taiKhoan;
            Presentation.SerTaikhoan.LoginResponse retVal = ((Presentation.SerTaikhoan.SerTaikhoanSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerTaikhoan.LoginResponse> Presentation.SerTaikhoan.SerTaikhoanSoap.LoginAsync(Presentation.SerTaikhoan.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerTaikhoan.LoginResponse> LoginAsync(Presentation.SerTaikhoan.DTTaikhoan taiKhoan) {
            Presentation.SerTaikhoan.LoginRequest inValue = new Presentation.SerTaikhoan.LoginRequest();
            inValue.Body = new Presentation.SerTaikhoan.LoginRequestBody();
            inValue.Body.taiKhoan = taiKhoan;
            return ((Presentation.SerTaikhoan.SerTaikhoanSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerTaikhoan.ChangePassResponse Presentation.SerTaikhoan.SerTaikhoanSoap.ChangePass(Presentation.SerTaikhoan.ChangePassRequest request) {
            return base.Channel.ChangePass(request);
        }
        
        public bool ChangePass(Presentation.SerTaikhoan.DTTaikhoan taiKhoan, int oldp) {
            Presentation.SerTaikhoan.ChangePassRequest inValue = new Presentation.SerTaikhoan.ChangePassRequest();
            inValue.Body = new Presentation.SerTaikhoan.ChangePassRequestBody();
            inValue.Body.taiKhoan = taiKhoan;
            inValue.Body.oldp = oldp;
            Presentation.SerTaikhoan.ChangePassResponse retVal = ((Presentation.SerTaikhoan.SerTaikhoanSoap)(this)).ChangePass(inValue);
            return retVal.Body.ChangePassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerTaikhoan.ChangePassResponse> Presentation.SerTaikhoan.SerTaikhoanSoap.ChangePassAsync(Presentation.SerTaikhoan.ChangePassRequest request) {
            return base.Channel.ChangePassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerTaikhoan.ChangePassResponse> ChangePassAsync(Presentation.SerTaikhoan.DTTaikhoan taiKhoan, int oldp) {
            Presentation.SerTaikhoan.ChangePassRequest inValue = new Presentation.SerTaikhoan.ChangePassRequest();
            inValue.Body = new Presentation.SerTaikhoan.ChangePassRequestBody();
            inValue.Body.taiKhoan = taiKhoan;
            inValue.Body.oldp = oldp;
            return ((Presentation.SerTaikhoan.SerTaikhoanSoap)(this)).ChangePassAsync(inValue);
        }
    }
}
