//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.SerLopHP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTLophocphan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTLophocphan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLopHocPhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaMonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenMonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaGiangVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenGiangVienField;
        
        private byte HocKyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamHocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaLopHocPhan {
            get {
                return this.MaLopHocPhanField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLopHocPhanField, value) != true)) {
                    this.MaLopHocPhanField = value;
                    this.RaisePropertyChanged("MaLopHocPhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaMon {
            get {
                return this.MaMonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaMonField, value) != true)) {
                    this.MaMonField = value;
                    this.RaisePropertyChanged("MaMon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenMon {
            get {
                return this.TenMonField;
            }
            set {
                if ((object.ReferenceEquals(this.TenMonField, value) != true)) {
                    this.TenMonField = value;
                    this.RaisePropertyChanged("TenMon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MaGiangVien {
            get {
                return this.MaGiangVienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaGiangVienField, value) != true)) {
                    this.MaGiangVienField = value;
                    this.RaisePropertyChanged("MaGiangVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TenGiangVien {
            get {
                return this.TenGiangVienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenGiangVienField, value) != true)) {
                    this.TenGiangVienField = value;
                    this.RaisePropertyChanged("TenGiangVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public byte HocKy {
            get {
                return this.HocKyField;
            }
            set {
                if ((this.HocKyField.Equals(value) != true)) {
                    this.HocKyField = value;
                    this.RaisePropertyChanged("HocKy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NamHoc {
            get {
                return this.NamHocField;
            }
            set {
                if ((object.ReferenceEquals(this.NamHocField, value) != true)) {
                    this.NamHocField = value;
                    this.RaisePropertyChanged("NamHoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTKhoa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTKhoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDienThoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SoDienThoai {
            get {
                return this.SoDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDienThoaiField, value) != true)) {
                    this.SoDienThoaiField = value;
                    this.RaisePropertyChanged("SoDienThoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTGiangvien", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTGiangvien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaGiangVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenGiangVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoDemField;
        
        private bool GioiTinhField;
        
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HocViField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaGiangVien {
            get {
                return this.MaGiangVienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaGiangVienField, value) != true)) {
                    this.MaGiangVienField = value;
                    this.RaisePropertyChanged("MaGiangVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenGiangVien {
            get {
                return this.TenGiangVienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenGiangVienField, value) != true)) {
                    this.TenGiangVienField = value;
                    this.RaisePropertyChanged("TenGiangVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HoDem {
            get {
                return this.HoDemField;
            }
            set {
                if ((object.ReferenceEquals(this.HoDemField, value) != true)) {
                    this.HoDemField = value;
                    this.RaisePropertyChanged("HoDem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((this.GioiTinhField.Equals(value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string HocVi {
            get {
                return this.HocViField;
            }
            set {
                if ((object.ReferenceEquals(this.HocViField, value) != true)) {
                    this.HocViField = value;
                    this.RaisePropertyChanged("HocVi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTMonhoc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTMonhoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaMonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenMonField;
        
        private byte SoTinChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaMon {
            get {
                return this.MaMonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaMonField, value) != true)) {
                    this.MaMonField = value;
                    this.RaisePropertyChanged("MaMon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenMon {
            get {
                return this.TenMonField;
            }
            set {
                if ((object.ReferenceEquals(this.TenMonField, value) != true)) {
                    this.TenMonField = value;
                    this.RaisePropertyChanged("TenMon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public byte SoTinChi {
            get {
                return this.SoTinChiField;
            }
            set {
                if ((this.SoTinChiField.Equals(value) != true)) {
                    this.SoTinChiField = value;
                    this.RaisePropertyChanged("SoTinChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SerLopHP.SerLopHPSoap")]
    public interface SerLopHPSoap {
        
        // CODEGEN: Generating message contract since element name GetAllLHPResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLHP", ReplyAction="*")]
        Presentation.SerLopHP.GetAllLHPResponse GetAllLHP(Presentation.SerLopHP.GetAllLHPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLHP", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerLopHP.GetAllLHPResponse> GetAllLHPAsync(Presentation.SerLopHP.GetAllLHPRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllKhoaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKhoa", ReplyAction="*")]
        Presentation.SerLopHP.GetAllKhoaResponse GetAllKhoa(Presentation.SerLopHP.GetAllKhoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKhoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerLopHP.GetAllKhoaResponse> GetAllKhoaAsync(Presentation.SerLopHP.GetAllKhoaRequest request);
        
        // CODEGEN: Generating message contract since element name mak from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGiangVienByKHoa", ReplyAction="*")]
        Presentation.SerLopHP.GetGiangVienByKHoaResponse GetGiangVienByKHoa(Presentation.SerLopHP.GetGiangVienByKHoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGiangVienByKHoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerLopHP.GetGiangVienByKHoaResponse> GetGiangVienByKHoaAsync(Presentation.SerLopHP.GetGiangVienByKHoaRequest request);
        
        // CODEGEN: Generating message contract since element name GetMonHocResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMonHoc", ReplyAction="*")]
        Presentation.SerLopHP.GetMonHocResponse GetMonHoc(Presentation.SerLopHP.GetMonHocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMonHoc", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerLopHP.GetMonHocResponse> GetMonHocAsync(Presentation.SerLopHP.GetMonHocRequest request);
        
        // CODEGEN: Generating message contract since element name lop from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLopHP", ReplyAction="*")]
        Presentation.SerLopHP.AddLopHPResponse AddLopHP(Presentation.SerLopHP.AddLopHPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLopHP", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerLopHP.AddLopHPResponse> AddLopHPAsync(Presentation.SerLopHP.AddLopHPRequest request);
        
        // CODEGEN: Generating message contract since element name lop from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditLopHP", ReplyAction="*")]
        Presentation.SerLopHP.EditLopHPResponse EditLopHP(Presentation.SerLopHP.EditLopHPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditLopHP", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerLopHP.EditLopHPResponse> EditLopHPAsync(Presentation.SerLopHP.EditLopHPRequest request);
        
        // CODEGEN: Generating message contract since element name lop from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteLopHP", ReplyAction="*")]
        Presentation.SerLopHP.DeleteLopHPResponse DeleteLopHP(Presentation.SerLopHP.DeleteLopHPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteLopHP", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerLopHP.DeleteLopHPResponse> DeleteLopHPAsync(Presentation.SerLopHP.DeleteLopHPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllLHPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllLHP", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.GetAllLHPRequestBody Body;
        
        public GetAllLHPRequest() {
        }
        
        public GetAllLHPRequest(Presentation.SerLopHP.GetAllLHPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllLHPRequestBody {
        
        public GetAllLHPRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllLHPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllLHPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.GetAllLHPResponseBody Body;
        
        public GetAllLHPResponse() {
        }
        
        public GetAllLHPResponse(Presentation.SerLopHP.GetAllLHPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllLHPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerLopHP.DTLophocphan[] GetAllLHPResult;
        
        public GetAllLHPResponseBody() {
        }
        
        public GetAllLHPResponseBody(Presentation.SerLopHP.DTLophocphan[] GetAllLHPResult) {
            this.GetAllLHPResult = GetAllLHPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKhoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKhoa", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.GetAllKhoaRequestBody Body;
        
        public GetAllKhoaRequest() {
        }
        
        public GetAllKhoaRequest(Presentation.SerLopHP.GetAllKhoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllKhoaRequestBody {
        
        public GetAllKhoaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKhoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKhoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.GetAllKhoaResponseBody Body;
        
        public GetAllKhoaResponse() {
        }
        
        public GetAllKhoaResponse(Presentation.SerLopHP.GetAllKhoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKhoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerLopHP.DTKhoa[] GetAllKhoaResult;
        
        public GetAllKhoaResponseBody() {
        }
        
        public GetAllKhoaResponseBody(Presentation.SerLopHP.DTKhoa[] GetAllKhoaResult) {
            this.GetAllKhoaResult = GetAllKhoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGiangVienByKHoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGiangVienByKHoa", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.GetGiangVienByKHoaRequestBody Body;
        
        public GetGiangVienByKHoaRequest() {
        }
        
        public GetGiangVienByKHoaRequest(Presentation.SerLopHP.GetGiangVienByKHoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGiangVienByKHoaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mak;
        
        public GetGiangVienByKHoaRequestBody() {
        }
        
        public GetGiangVienByKHoaRequestBody(string mak) {
            this.mak = mak;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGiangVienByKHoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGiangVienByKHoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.GetGiangVienByKHoaResponseBody Body;
        
        public GetGiangVienByKHoaResponse() {
        }
        
        public GetGiangVienByKHoaResponse(Presentation.SerLopHP.GetGiangVienByKHoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGiangVienByKHoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerLopHP.DTGiangvien[] GetGiangVienByKHoaResult;
        
        public GetGiangVienByKHoaResponseBody() {
        }
        
        public GetGiangVienByKHoaResponseBody(Presentation.SerLopHP.DTGiangvien[] GetGiangVienByKHoaResult) {
            this.GetGiangVienByKHoaResult = GetGiangVienByKHoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonHocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMonHoc", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.GetMonHocRequestBody Body;
        
        public GetMonHocRequest() {
        }
        
        public GetMonHocRequest(Presentation.SerLopHP.GetMonHocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMonHocRequestBody {
        
        public GetMonHocRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonHocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMonHocResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.GetMonHocResponseBody Body;
        
        public GetMonHocResponse() {
        }
        
        public GetMonHocResponse(Presentation.SerLopHP.GetMonHocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMonHocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerLopHP.DTMonhoc[] GetMonHocResult;
        
        public GetMonHocResponseBody() {
        }
        
        public GetMonHocResponseBody(Presentation.SerLopHP.DTMonhoc[] GetMonHocResult) {
            this.GetMonHocResult = GetMonHocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLopHPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLopHP", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.AddLopHPRequestBody Body;
        
        public AddLopHPRequest() {
        }
        
        public AddLopHPRequest(Presentation.SerLopHP.AddLopHPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddLopHPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerLopHP.DTLophocphan lop;
        
        public AddLopHPRequestBody() {
        }
        
        public AddLopHPRequestBody(Presentation.SerLopHP.DTLophocphan lop) {
            this.lop = lop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLopHPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLopHPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.AddLopHPResponseBody Body;
        
        public AddLopHPResponse() {
        }
        
        public AddLopHPResponse(Presentation.SerLopHP.AddLopHPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddLopHPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddLopHPResult;
        
        public AddLopHPResponseBody() {
        }
        
        public AddLopHPResponseBody(bool AddLopHPResult) {
            this.AddLopHPResult = AddLopHPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditLopHPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditLopHP", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.EditLopHPRequestBody Body;
        
        public EditLopHPRequest() {
        }
        
        public EditLopHPRequest(Presentation.SerLopHP.EditLopHPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditLopHPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerLopHP.DTLophocphan lop;
        
        public EditLopHPRequestBody() {
        }
        
        public EditLopHPRequestBody(Presentation.SerLopHP.DTLophocphan lop) {
            this.lop = lop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditLopHPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditLopHPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.EditLopHPResponseBody Body;
        
        public EditLopHPResponse() {
        }
        
        public EditLopHPResponse(Presentation.SerLopHP.EditLopHPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditLopHPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditLopHPResult;
        
        public EditLopHPResponseBody() {
        }
        
        public EditLopHPResponseBody(bool EditLopHPResult) {
            this.EditLopHPResult = EditLopHPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteLopHPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteLopHP", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.DeleteLopHPRequestBody Body;
        
        public DeleteLopHPRequest() {
        }
        
        public DeleteLopHPRequest(Presentation.SerLopHP.DeleteLopHPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteLopHPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerLopHP.DTLophocphan lop;
        
        public DeleteLopHPRequestBody() {
        }
        
        public DeleteLopHPRequestBody(Presentation.SerLopHP.DTLophocphan lop) {
            this.lop = lop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteLopHPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteLopHPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerLopHP.DeleteLopHPResponseBody Body;
        
        public DeleteLopHPResponse() {
        }
        
        public DeleteLopHPResponse(Presentation.SerLopHP.DeleteLopHPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteLopHPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteLopHPResult;
        
        public DeleteLopHPResponseBody() {
        }
        
        public DeleteLopHPResponseBody(bool DeleteLopHPResult) {
            this.DeleteLopHPResult = DeleteLopHPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SerLopHPSoapChannel : Presentation.SerLopHP.SerLopHPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerLopHPSoapClient : System.ServiceModel.ClientBase<Presentation.SerLopHP.SerLopHPSoap>, Presentation.SerLopHP.SerLopHPSoap {
        
        public SerLopHPSoapClient() {
        }
        
        public SerLopHPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerLopHPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerLopHPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerLopHPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerLopHP.GetAllLHPResponse Presentation.SerLopHP.SerLopHPSoap.GetAllLHP(Presentation.SerLopHP.GetAllLHPRequest request) {
            return base.Channel.GetAllLHP(request);
        }
        
        public Presentation.SerLopHP.DTLophocphan[] GetAllLHP() {
            Presentation.SerLopHP.GetAllLHPRequest inValue = new Presentation.SerLopHP.GetAllLHPRequest();
            inValue.Body = new Presentation.SerLopHP.GetAllLHPRequestBody();
            Presentation.SerLopHP.GetAllLHPResponse retVal = ((Presentation.SerLopHP.SerLopHPSoap)(this)).GetAllLHP(inValue);
            return retVal.Body.GetAllLHPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerLopHP.GetAllLHPResponse> Presentation.SerLopHP.SerLopHPSoap.GetAllLHPAsync(Presentation.SerLopHP.GetAllLHPRequest request) {
            return base.Channel.GetAllLHPAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerLopHP.GetAllLHPResponse> GetAllLHPAsync() {
            Presentation.SerLopHP.GetAllLHPRequest inValue = new Presentation.SerLopHP.GetAllLHPRequest();
            inValue.Body = new Presentation.SerLopHP.GetAllLHPRequestBody();
            return ((Presentation.SerLopHP.SerLopHPSoap)(this)).GetAllLHPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerLopHP.GetAllKhoaResponse Presentation.SerLopHP.SerLopHPSoap.GetAllKhoa(Presentation.SerLopHP.GetAllKhoaRequest request) {
            return base.Channel.GetAllKhoa(request);
        }
        
        public Presentation.SerLopHP.DTKhoa[] GetAllKhoa() {
            Presentation.SerLopHP.GetAllKhoaRequest inValue = new Presentation.SerLopHP.GetAllKhoaRequest();
            inValue.Body = new Presentation.SerLopHP.GetAllKhoaRequestBody();
            Presentation.SerLopHP.GetAllKhoaResponse retVal = ((Presentation.SerLopHP.SerLopHPSoap)(this)).GetAllKhoa(inValue);
            return retVal.Body.GetAllKhoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerLopHP.GetAllKhoaResponse> Presentation.SerLopHP.SerLopHPSoap.GetAllKhoaAsync(Presentation.SerLopHP.GetAllKhoaRequest request) {
            return base.Channel.GetAllKhoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerLopHP.GetAllKhoaResponse> GetAllKhoaAsync() {
            Presentation.SerLopHP.GetAllKhoaRequest inValue = new Presentation.SerLopHP.GetAllKhoaRequest();
            inValue.Body = new Presentation.SerLopHP.GetAllKhoaRequestBody();
            return ((Presentation.SerLopHP.SerLopHPSoap)(this)).GetAllKhoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerLopHP.GetGiangVienByKHoaResponse Presentation.SerLopHP.SerLopHPSoap.GetGiangVienByKHoa(Presentation.SerLopHP.GetGiangVienByKHoaRequest request) {
            return base.Channel.GetGiangVienByKHoa(request);
        }
        
        public Presentation.SerLopHP.DTGiangvien[] GetGiangVienByKHoa(string mak) {
            Presentation.SerLopHP.GetGiangVienByKHoaRequest inValue = new Presentation.SerLopHP.GetGiangVienByKHoaRequest();
            inValue.Body = new Presentation.SerLopHP.GetGiangVienByKHoaRequestBody();
            inValue.Body.mak = mak;
            Presentation.SerLopHP.GetGiangVienByKHoaResponse retVal = ((Presentation.SerLopHP.SerLopHPSoap)(this)).GetGiangVienByKHoa(inValue);
            return retVal.Body.GetGiangVienByKHoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerLopHP.GetGiangVienByKHoaResponse> Presentation.SerLopHP.SerLopHPSoap.GetGiangVienByKHoaAsync(Presentation.SerLopHP.GetGiangVienByKHoaRequest request) {
            return base.Channel.GetGiangVienByKHoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerLopHP.GetGiangVienByKHoaResponse> GetGiangVienByKHoaAsync(string mak) {
            Presentation.SerLopHP.GetGiangVienByKHoaRequest inValue = new Presentation.SerLopHP.GetGiangVienByKHoaRequest();
            inValue.Body = new Presentation.SerLopHP.GetGiangVienByKHoaRequestBody();
            inValue.Body.mak = mak;
            return ((Presentation.SerLopHP.SerLopHPSoap)(this)).GetGiangVienByKHoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerLopHP.GetMonHocResponse Presentation.SerLopHP.SerLopHPSoap.GetMonHoc(Presentation.SerLopHP.GetMonHocRequest request) {
            return base.Channel.GetMonHoc(request);
        }
        
        public Presentation.SerLopHP.DTMonhoc[] GetMonHoc() {
            Presentation.SerLopHP.GetMonHocRequest inValue = new Presentation.SerLopHP.GetMonHocRequest();
            inValue.Body = new Presentation.SerLopHP.GetMonHocRequestBody();
            Presentation.SerLopHP.GetMonHocResponse retVal = ((Presentation.SerLopHP.SerLopHPSoap)(this)).GetMonHoc(inValue);
            return retVal.Body.GetMonHocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerLopHP.GetMonHocResponse> Presentation.SerLopHP.SerLopHPSoap.GetMonHocAsync(Presentation.SerLopHP.GetMonHocRequest request) {
            return base.Channel.GetMonHocAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerLopHP.GetMonHocResponse> GetMonHocAsync() {
            Presentation.SerLopHP.GetMonHocRequest inValue = new Presentation.SerLopHP.GetMonHocRequest();
            inValue.Body = new Presentation.SerLopHP.GetMonHocRequestBody();
            return ((Presentation.SerLopHP.SerLopHPSoap)(this)).GetMonHocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerLopHP.AddLopHPResponse Presentation.SerLopHP.SerLopHPSoap.AddLopHP(Presentation.SerLopHP.AddLopHPRequest request) {
            return base.Channel.AddLopHP(request);
        }
        
        public bool AddLopHP(Presentation.SerLopHP.DTLophocphan lop) {
            Presentation.SerLopHP.AddLopHPRequest inValue = new Presentation.SerLopHP.AddLopHPRequest();
            inValue.Body = new Presentation.SerLopHP.AddLopHPRequestBody();
            inValue.Body.lop = lop;
            Presentation.SerLopHP.AddLopHPResponse retVal = ((Presentation.SerLopHP.SerLopHPSoap)(this)).AddLopHP(inValue);
            return retVal.Body.AddLopHPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerLopHP.AddLopHPResponse> Presentation.SerLopHP.SerLopHPSoap.AddLopHPAsync(Presentation.SerLopHP.AddLopHPRequest request) {
            return base.Channel.AddLopHPAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerLopHP.AddLopHPResponse> AddLopHPAsync(Presentation.SerLopHP.DTLophocphan lop) {
            Presentation.SerLopHP.AddLopHPRequest inValue = new Presentation.SerLopHP.AddLopHPRequest();
            inValue.Body = new Presentation.SerLopHP.AddLopHPRequestBody();
            inValue.Body.lop = lop;
            return ((Presentation.SerLopHP.SerLopHPSoap)(this)).AddLopHPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerLopHP.EditLopHPResponse Presentation.SerLopHP.SerLopHPSoap.EditLopHP(Presentation.SerLopHP.EditLopHPRequest request) {
            return base.Channel.EditLopHP(request);
        }
        
        public bool EditLopHP(Presentation.SerLopHP.DTLophocphan lop) {
            Presentation.SerLopHP.EditLopHPRequest inValue = new Presentation.SerLopHP.EditLopHPRequest();
            inValue.Body = new Presentation.SerLopHP.EditLopHPRequestBody();
            inValue.Body.lop = lop;
            Presentation.SerLopHP.EditLopHPResponse retVal = ((Presentation.SerLopHP.SerLopHPSoap)(this)).EditLopHP(inValue);
            return retVal.Body.EditLopHPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerLopHP.EditLopHPResponse> Presentation.SerLopHP.SerLopHPSoap.EditLopHPAsync(Presentation.SerLopHP.EditLopHPRequest request) {
            return base.Channel.EditLopHPAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerLopHP.EditLopHPResponse> EditLopHPAsync(Presentation.SerLopHP.DTLophocphan lop) {
            Presentation.SerLopHP.EditLopHPRequest inValue = new Presentation.SerLopHP.EditLopHPRequest();
            inValue.Body = new Presentation.SerLopHP.EditLopHPRequestBody();
            inValue.Body.lop = lop;
            return ((Presentation.SerLopHP.SerLopHPSoap)(this)).EditLopHPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerLopHP.DeleteLopHPResponse Presentation.SerLopHP.SerLopHPSoap.DeleteLopHP(Presentation.SerLopHP.DeleteLopHPRequest request) {
            return base.Channel.DeleteLopHP(request);
        }
        
        public bool DeleteLopHP(Presentation.SerLopHP.DTLophocphan lop) {
            Presentation.SerLopHP.DeleteLopHPRequest inValue = new Presentation.SerLopHP.DeleteLopHPRequest();
            inValue.Body = new Presentation.SerLopHP.DeleteLopHPRequestBody();
            inValue.Body.lop = lop;
            Presentation.SerLopHP.DeleteLopHPResponse retVal = ((Presentation.SerLopHP.SerLopHPSoap)(this)).DeleteLopHP(inValue);
            return retVal.Body.DeleteLopHPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerLopHP.DeleteLopHPResponse> Presentation.SerLopHP.SerLopHPSoap.DeleteLopHPAsync(Presentation.SerLopHP.DeleteLopHPRequest request) {
            return base.Channel.DeleteLopHPAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerLopHP.DeleteLopHPResponse> DeleteLopHPAsync(Presentation.SerLopHP.DTLophocphan lop) {
            Presentation.SerLopHP.DeleteLopHPRequest inValue = new Presentation.SerLopHP.DeleteLopHPRequest();
            inValue.Body = new Presentation.SerLopHP.DeleteLopHPRequestBody();
            inValue.Body.lop = lop;
            return ((Presentation.SerLopHP.SerLopHPSoap)(this)).DeleteLopHPAsync(inValue);
        }
    }
}
