//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.SerMonhoc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTMonhoc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTMonhoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaMonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenMonField;
        
        private byte SoTinChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaMon {
            get {
                return this.MaMonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaMonField, value) != true)) {
                    this.MaMonField = value;
                    this.RaisePropertyChanged("MaMon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenMon {
            get {
                return this.TenMonField;
            }
            set {
                if ((object.ReferenceEquals(this.TenMonField, value) != true)) {
                    this.TenMonField = value;
                    this.RaisePropertyChanged("TenMon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public byte SoTinChi {
            get {
                return this.SoTinChiField;
            }
            set {
                if ((this.SoTinChiField.Equals(value) != true)) {
                    this.SoTinChiField = value;
                    this.RaisePropertyChanged("SoTinChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTKhoa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTKhoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDienThoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SoDienThoai {
            get {
                return this.SoDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDienThoaiField, value) != true)) {
                    this.SoDienThoaiField = value;
                    this.RaisePropertyChanged("SoDienThoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SerMonhoc.SerMonhocSoap")]
    public interface SerMonhocSoap {
        
        // CODEGEN: Generating message contract since element name GetAllMonHocResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMonHoc", ReplyAction="*")]
        Presentation.SerMonhoc.GetAllMonHocResponse GetAllMonHoc(Presentation.SerMonhoc.GetAllMonHocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMonHoc", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerMonhoc.GetAllMonHocResponse> GetAllMonHocAsync(Presentation.SerMonhoc.GetAllMonHocRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllKhoaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKhoa", ReplyAction="*")]
        Presentation.SerMonhoc.GetAllKhoaResponse GetAllKhoa(Presentation.SerMonhoc.GetAllKhoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKhoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerMonhoc.GetAllKhoaResponse> GetAllKhoaAsync(Presentation.SerMonhoc.GetAllKhoaRequest request);
        
        // CODEGEN: Generating message contract since element name mon from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMonHoc", ReplyAction="*")]
        Presentation.SerMonhoc.AddMonHocResponse AddMonHoc(Presentation.SerMonhoc.AddMonHocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMonHoc", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerMonhoc.AddMonHocResponse> AddMonHocAsync(Presentation.SerMonhoc.AddMonHocRequest request);
        
        // CODEGEN: Generating message contract since element name mon from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMonHoc", ReplyAction="*")]
        Presentation.SerMonhoc.UpdateMonHocResponse UpdateMonHoc(Presentation.SerMonhoc.UpdateMonHocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMonHoc", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerMonhoc.UpdateMonHocResponse> UpdateMonHocAsync(Presentation.SerMonhoc.UpdateMonHocRequest request);
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMonHoc", ReplyAction="*")]
        Presentation.SerMonhoc.DeleteMonHocResponse DeleteMonHoc(Presentation.SerMonhoc.DeleteMonHocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMonHoc", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerMonhoc.DeleteMonHocResponse> DeleteMonHocAsync(Presentation.SerMonhoc.DeleteMonHocRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMonHocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMonHoc", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerMonhoc.GetAllMonHocRequestBody Body;
        
        public GetAllMonHocRequest() {
        }
        
        public GetAllMonHocRequest(Presentation.SerMonhoc.GetAllMonHocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMonHocRequestBody {
        
        public GetAllMonHocRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMonHocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMonHocResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerMonhoc.GetAllMonHocResponseBody Body;
        
        public GetAllMonHocResponse() {
        }
        
        public GetAllMonHocResponse(Presentation.SerMonhoc.GetAllMonHocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMonHocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerMonhoc.DTMonhoc[] GetAllMonHocResult;
        
        public GetAllMonHocResponseBody() {
        }
        
        public GetAllMonHocResponseBody(Presentation.SerMonhoc.DTMonhoc[] GetAllMonHocResult) {
            this.GetAllMonHocResult = GetAllMonHocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKhoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKhoa", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerMonhoc.GetAllKhoaRequestBody Body;
        
        public GetAllKhoaRequest() {
        }
        
        public GetAllKhoaRequest(Presentation.SerMonhoc.GetAllKhoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllKhoaRequestBody {
        
        public GetAllKhoaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKhoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKhoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerMonhoc.GetAllKhoaResponseBody Body;
        
        public GetAllKhoaResponse() {
        }
        
        public GetAllKhoaResponse(Presentation.SerMonhoc.GetAllKhoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKhoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerMonhoc.DTKhoa[] GetAllKhoaResult;
        
        public GetAllKhoaResponseBody() {
        }
        
        public GetAllKhoaResponseBody(Presentation.SerMonhoc.DTKhoa[] GetAllKhoaResult) {
            this.GetAllKhoaResult = GetAllKhoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMonHocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMonHoc", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerMonhoc.AddMonHocRequestBody Body;
        
        public AddMonHocRequest() {
        }
        
        public AddMonHocRequest(Presentation.SerMonhoc.AddMonHocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMonHocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerMonhoc.DTMonhoc mon;
        
        public AddMonHocRequestBody() {
        }
        
        public AddMonHocRequestBody(Presentation.SerMonhoc.DTMonhoc mon) {
            this.mon = mon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMonHocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMonHocResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerMonhoc.AddMonHocResponseBody Body;
        
        public AddMonHocResponse() {
        }
        
        public AddMonHocResponse(Presentation.SerMonhoc.AddMonHocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMonHocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddMonHocResult;
        
        public AddMonHocResponseBody() {
        }
        
        public AddMonHocResponseBody(bool AddMonHocResult) {
            this.AddMonHocResult = AddMonHocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMonHocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMonHoc", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerMonhoc.UpdateMonHocRequestBody Body;
        
        public UpdateMonHocRequest() {
        }
        
        public UpdateMonHocRequest(Presentation.SerMonhoc.UpdateMonHocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMonHocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerMonhoc.DTMonhoc mon;
        
        public UpdateMonHocRequestBody() {
        }
        
        public UpdateMonHocRequestBody(Presentation.SerMonhoc.DTMonhoc mon) {
            this.mon = mon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMonHocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMonHocResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerMonhoc.UpdateMonHocResponseBody Body;
        
        public UpdateMonHocResponse() {
        }
        
        public UpdateMonHocResponse(Presentation.SerMonhoc.UpdateMonHocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMonHocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateMonHocResult;
        
        public UpdateMonHocResponseBody() {
        }
        
        public UpdateMonHocResponseBody(bool UpdateMonHocResult) {
            this.UpdateMonHocResult = UpdateMonHocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMonHocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMonHoc", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerMonhoc.DeleteMonHocRequestBody Body;
        
        public DeleteMonHocRequest() {
        }
        
        public DeleteMonHocRequest(Presentation.SerMonhoc.DeleteMonHocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMonHocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        public DeleteMonHocRequestBody() {
        }
        
        public DeleteMonHocRequestBody(string ma) {
            this.ma = ma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMonHocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMonHocResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerMonhoc.DeleteMonHocResponseBody Body;
        
        public DeleteMonHocResponse() {
        }
        
        public DeleteMonHocResponse(Presentation.SerMonhoc.DeleteMonHocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMonHocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteMonHocResult;
        
        public DeleteMonHocResponseBody() {
        }
        
        public DeleteMonHocResponseBody(bool DeleteMonHocResult) {
            this.DeleteMonHocResult = DeleteMonHocResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SerMonhocSoapChannel : Presentation.SerMonhoc.SerMonhocSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerMonhocSoapClient : System.ServiceModel.ClientBase<Presentation.SerMonhoc.SerMonhocSoap>, Presentation.SerMonhoc.SerMonhocSoap {
        
        public SerMonhocSoapClient() {
        }
        
        public SerMonhocSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerMonhocSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerMonhocSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerMonhocSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerMonhoc.GetAllMonHocResponse Presentation.SerMonhoc.SerMonhocSoap.GetAllMonHoc(Presentation.SerMonhoc.GetAllMonHocRequest request) {
            return base.Channel.GetAllMonHoc(request);
        }
        
        public Presentation.SerMonhoc.DTMonhoc[] GetAllMonHoc() {
            Presentation.SerMonhoc.GetAllMonHocRequest inValue = new Presentation.SerMonhoc.GetAllMonHocRequest();
            inValue.Body = new Presentation.SerMonhoc.GetAllMonHocRequestBody();
            Presentation.SerMonhoc.GetAllMonHocResponse retVal = ((Presentation.SerMonhoc.SerMonhocSoap)(this)).GetAllMonHoc(inValue);
            return retVal.Body.GetAllMonHocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerMonhoc.GetAllMonHocResponse> Presentation.SerMonhoc.SerMonhocSoap.GetAllMonHocAsync(Presentation.SerMonhoc.GetAllMonHocRequest request) {
            return base.Channel.GetAllMonHocAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerMonhoc.GetAllMonHocResponse> GetAllMonHocAsync() {
            Presentation.SerMonhoc.GetAllMonHocRequest inValue = new Presentation.SerMonhoc.GetAllMonHocRequest();
            inValue.Body = new Presentation.SerMonhoc.GetAllMonHocRequestBody();
            return ((Presentation.SerMonhoc.SerMonhocSoap)(this)).GetAllMonHocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerMonhoc.GetAllKhoaResponse Presentation.SerMonhoc.SerMonhocSoap.GetAllKhoa(Presentation.SerMonhoc.GetAllKhoaRequest request) {
            return base.Channel.GetAllKhoa(request);
        }
        
        public Presentation.SerMonhoc.DTKhoa[] GetAllKhoa() {
            Presentation.SerMonhoc.GetAllKhoaRequest inValue = new Presentation.SerMonhoc.GetAllKhoaRequest();
            inValue.Body = new Presentation.SerMonhoc.GetAllKhoaRequestBody();
            Presentation.SerMonhoc.GetAllKhoaResponse retVal = ((Presentation.SerMonhoc.SerMonhocSoap)(this)).GetAllKhoa(inValue);
            return retVal.Body.GetAllKhoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerMonhoc.GetAllKhoaResponse> Presentation.SerMonhoc.SerMonhocSoap.GetAllKhoaAsync(Presentation.SerMonhoc.GetAllKhoaRequest request) {
            return base.Channel.GetAllKhoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerMonhoc.GetAllKhoaResponse> GetAllKhoaAsync() {
            Presentation.SerMonhoc.GetAllKhoaRequest inValue = new Presentation.SerMonhoc.GetAllKhoaRequest();
            inValue.Body = new Presentation.SerMonhoc.GetAllKhoaRequestBody();
            return ((Presentation.SerMonhoc.SerMonhocSoap)(this)).GetAllKhoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerMonhoc.AddMonHocResponse Presentation.SerMonhoc.SerMonhocSoap.AddMonHoc(Presentation.SerMonhoc.AddMonHocRequest request) {
            return base.Channel.AddMonHoc(request);
        }
        
        public bool AddMonHoc(Presentation.SerMonhoc.DTMonhoc mon) {
            Presentation.SerMonhoc.AddMonHocRequest inValue = new Presentation.SerMonhoc.AddMonHocRequest();
            inValue.Body = new Presentation.SerMonhoc.AddMonHocRequestBody();
            inValue.Body.mon = mon;
            Presentation.SerMonhoc.AddMonHocResponse retVal = ((Presentation.SerMonhoc.SerMonhocSoap)(this)).AddMonHoc(inValue);
            return retVal.Body.AddMonHocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerMonhoc.AddMonHocResponse> Presentation.SerMonhoc.SerMonhocSoap.AddMonHocAsync(Presentation.SerMonhoc.AddMonHocRequest request) {
            return base.Channel.AddMonHocAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerMonhoc.AddMonHocResponse> AddMonHocAsync(Presentation.SerMonhoc.DTMonhoc mon) {
            Presentation.SerMonhoc.AddMonHocRequest inValue = new Presentation.SerMonhoc.AddMonHocRequest();
            inValue.Body = new Presentation.SerMonhoc.AddMonHocRequestBody();
            inValue.Body.mon = mon;
            return ((Presentation.SerMonhoc.SerMonhocSoap)(this)).AddMonHocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerMonhoc.UpdateMonHocResponse Presentation.SerMonhoc.SerMonhocSoap.UpdateMonHoc(Presentation.SerMonhoc.UpdateMonHocRequest request) {
            return base.Channel.UpdateMonHoc(request);
        }
        
        public bool UpdateMonHoc(Presentation.SerMonhoc.DTMonhoc mon) {
            Presentation.SerMonhoc.UpdateMonHocRequest inValue = new Presentation.SerMonhoc.UpdateMonHocRequest();
            inValue.Body = new Presentation.SerMonhoc.UpdateMonHocRequestBody();
            inValue.Body.mon = mon;
            Presentation.SerMonhoc.UpdateMonHocResponse retVal = ((Presentation.SerMonhoc.SerMonhocSoap)(this)).UpdateMonHoc(inValue);
            return retVal.Body.UpdateMonHocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerMonhoc.UpdateMonHocResponse> Presentation.SerMonhoc.SerMonhocSoap.UpdateMonHocAsync(Presentation.SerMonhoc.UpdateMonHocRequest request) {
            return base.Channel.UpdateMonHocAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerMonhoc.UpdateMonHocResponse> UpdateMonHocAsync(Presentation.SerMonhoc.DTMonhoc mon) {
            Presentation.SerMonhoc.UpdateMonHocRequest inValue = new Presentation.SerMonhoc.UpdateMonHocRequest();
            inValue.Body = new Presentation.SerMonhoc.UpdateMonHocRequestBody();
            inValue.Body.mon = mon;
            return ((Presentation.SerMonhoc.SerMonhocSoap)(this)).UpdateMonHocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerMonhoc.DeleteMonHocResponse Presentation.SerMonhoc.SerMonhocSoap.DeleteMonHoc(Presentation.SerMonhoc.DeleteMonHocRequest request) {
            return base.Channel.DeleteMonHoc(request);
        }
        
        public bool DeleteMonHoc(string ma) {
            Presentation.SerMonhoc.DeleteMonHocRequest inValue = new Presentation.SerMonhoc.DeleteMonHocRequest();
            inValue.Body = new Presentation.SerMonhoc.DeleteMonHocRequestBody();
            inValue.Body.ma = ma;
            Presentation.SerMonhoc.DeleteMonHocResponse retVal = ((Presentation.SerMonhoc.SerMonhocSoap)(this)).DeleteMonHoc(inValue);
            return retVal.Body.DeleteMonHocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerMonhoc.DeleteMonHocResponse> Presentation.SerMonhoc.SerMonhocSoap.DeleteMonHocAsync(Presentation.SerMonhoc.DeleteMonHocRequest request) {
            return base.Channel.DeleteMonHocAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerMonhoc.DeleteMonHocResponse> DeleteMonHocAsync(string ma) {
            Presentation.SerMonhoc.DeleteMonHocRequest inValue = new Presentation.SerMonhoc.DeleteMonHocRequest();
            inValue.Body = new Presentation.SerMonhoc.DeleteMonHocRequestBody();
            inValue.Body.ma = ma;
            return ((Presentation.SerMonhoc.SerMonhocSoap)(this)).DeleteMonHocAsync(inValue);
        }
    }
}
