//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.SerKhoa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTKhoa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTKhoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDienThoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SoDienThoai {
            get {
                return this.SoDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDienThoaiField, value) != true)) {
                    this.SoDienThoaiField = value;
                    this.RaisePropertyChanged("SoDienThoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SerKhoa.SerKhoaSoap")]
    public interface SerKhoaSoap {
        
        // CODEGEN: Generating message contract since element name GetAllKhoaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKhoa", ReplyAction="*")]
        Presentation.SerKhoa.GetAllKhoaResponse GetAllKhoa(Presentation.SerKhoa.GetAllKhoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKhoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerKhoa.GetAllKhoaResponse> GetAllKhoaAsync(Presentation.SerKhoa.GetAllKhoaRequest request);
        
        // CODEGEN: Generating message contract since element name khoa from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddKhoa", ReplyAction="*")]
        Presentation.SerKhoa.AddKhoaResponse AddKhoa(Presentation.SerKhoa.AddKhoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddKhoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerKhoa.AddKhoaResponse> AddKhoaAsync(Presentation.SerKhoa.AddKhoaRequest request);
        
        // CODEGEN: Generating message contract since element name khoa from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditKhoa", ReplyAction="*")]
        Presentation.SerKhoa.EditKhoaResponse EditKhoa(Presentation.SerKhoa.EditKhoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditKhoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerKhoa.EditKhoaResponse> EditKhoaAsync(Presentation.SerKhoa.EditKhoaRequest request);
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteKhoa", ReplyAction="*")]
        Presentation.SerKhoa.DeleteKhoaResponse DeleteKhoa(Presentation.SerKhoa.DeleteKhoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteKhoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerKhoa.DeleteKhoaResponse> DeleteKhoaAsync(Presentation.SerKhoa.DeleteKhoaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKhoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKhoa", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerKhoa.GetAllKhoaRequestBody Body;
        
        public GetAllKhoaRequest() {
        }
        
        public GetAllKhoaRequest(Presentation.SerKhoa.GetAllKhoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllKhoaRequestBody {
        
        public GetAllKhoaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKhoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKhoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerKhoa.GetAllKhoaResponseBody Body;
        
        public GetAllKhoaResponse() {
        }
        
        public GetAllKhoaResponse(Presentation.SerKhoa.GetAllKhoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKhoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerKhoa.DTKhoa[] GetAllKhoaResult;
        
        public GetAllKhoaResponseBody() {
        }
        
        public GetAllKhoaResponseBody(Presentation.SerKhoa.DTKhoa[] GetAllKhoaResult) {
            this.GetAllKhoaResult = GetAllKhoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddKhoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddKhoa", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerKhoa.AddKhoaRequestBody Body;
        
        public AddKhoaRequest() {
        }
        
        public AddKhoaRequest(Presentation.SerKhoa.AddKhoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddKhoaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerKhoa.DTKhoa khoa;
        
        public AddKhoaRequestBody() {
        }
        
        public AddKhoaRequestBody(Presentation.SerKhoa.DTKhoa khoa) {
            this.khoa = khoa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddKhoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddKhoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerKhoa.AddKhoaResponseBody Body;
        
        public AddKhoaResponse() {
        }
        
        public AddKhoaResponse(Presentation.SerKhoa.AddKhoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddKhoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddKhoaResult;
        
        public AddKhoaResponseBody() {
        }
        
        public AddKhoaResponseBody(int AddKhoaResult) {
            this.AddKhoaResult = AddKhoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditKhoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditKhoa", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerKhoa.EditKhoaRequestBody Body;
        
        public EditKhoaRequest() {
        }
        
        public EditKhoaRequest(Presentation.SerKhoa.EditKhoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditKhoaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerKhoa.DTKhoa khoa;
        
        public EditKhoaRequestBody() {
        }
        
        public EditKhoaRequestBody(Presentation.SerKhoa.DTKhoa khoa) {
            this.khoa = khoa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditKhoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditKhoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerKhoa.EditKhoaResponseBody Body;
        
        public EditKhoaResponse() {
        }
        
        public EditKhoaResponse(Presentation.SerKhoa.EditKhoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditKhoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int EditKhoaResult;
        
        public EditKhoaResponseBody() {
        }
        
        public EditKhoaResponseBody(int EditKhoaResult) {
            this.EditKhoaResult = EditKhoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteKhoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteKhoa", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerKhoa.DeleteKhoaRequestBody Body;
        
        public DeleteKhoaRequest() {
        }
        
        public DeleteKhoaRequest(Presentation.SerKhoa.DeleteKhoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteKhoaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        public DeleteKhoaRequestBody() {
        }
        
        public DeleteKhoaRequestBody(string ma) {
            this.ma = ma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteKhoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteKhoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerKhoa.DeleteKhoaResponseBody Body;
        
        public DeleteKhoaResponse() {
        }
        
        public DeleteKhoaResponse(Presentation.SerKhoa.DeleteKhoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteKhoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteKhoaResult;
        
        public DeleteKhoaResponseBody() {
        }
        
        public DeleteKhoaResponseBody(int DeleteKhoaResult) {
            this.DeleteKhoaResult = DeleteKhoaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SerKhoaSoapChannel : Presentation.SerKhoa.SerKhoaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerKhoaSoapClient : System.ServiceModel.ClientBase<Presentation.SerKhoa.SerKhoaSoap>, Presentation.SerKhoa.SerKhoaSoap {
        
        public SerKhoaSoapClient() {
        }
        
        public SerKhoaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerKhoaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerKhoaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerKhoaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerKhoa.GetAllKhoaResponse Presentation.SerKhoa.SerKhoaSoap.GetAllKhoa(Presentation.SerKhoa.GetAllKhoaRequest request) {
            return base.Channel.GetAllKhoa(request);
        }
        
        public Presentation.SerKhoa.DTKhoa[] GetAllKhoa() {
            Presentation.SerKhoa.GetAllKhoaRequest inValue = new Presentation.SerKhoa.GetAllKhoaRequest();
            inValue.Body = new Presentation.SerKhoa.GetAllKhoaRequestBody();
            Presentation.SerKhoa.GetAllKhoaResponse retVal = ((Presentation.SerKhoa.SerKhoaSoap)(this)).GetAllKhoa(inValue);
            return retVal.Body.GetAllKhoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerKhoa.GetAllKhoaResponse> Presentation.SerKhoa.SerKhoaSoap.GetAllKhoaAsync(Presentation.SerKhoa.GetAllKhoaRequest request) {
            return base.Channel.GetAllKhoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerKhoa.GetAllKhoaResponse> GetAllKhoaAsync() {
            Presentation.SerKhoa.GetAllKhoaRequest inValue = new Presentation.SerKhoa.GetAllKhoaRequest();
            inValue.Body = new Presentation.SerKhoa.GetAllKhoaRequestBody();
            return ((Presentation.SerKhoa.SerKhoaSoap)(this)).GetAllKhoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerKhoa.AddKhoaResponse Presentation.SerKhoa.SerKhoaSoap.AddKhoa(Presentation.SerKhoa.AddKhoaRequest request) {
            return base.Channel.AddKhoa(request);
        }
        
        public int AddKhoa(Presentation.SerKhoa.DTKhoa khoa) {
            Presentation.SerKhoa.AddKhoaRequest inValue = new Presentation.SerKhoa.AddKhoaRequest();
            inValue.Body = new Presentation.SerKhoa.AddKhoaRequestBody();
            inValue.Body.khoa = khoa;
            Presentation.SerKhoa.AddKhoaResponse retVal = ((Presentation.SerKhoa.SerKhoaSoap)(this)).AddKhoa(inValue);
            return retVal.Body.AddKhoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerKhoa.AddKhoaResponse> Presentation.SerKhoa.SerKhoaSoap.AddKhoaAsync(Presentation.SerKhoa.AddKhoaRequest request) {
            return base.Channel.AddKhoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerKhoa.AddKhoaResponse> AddKhoaAsync(Presentation.SerKhoa.DTKhoa khoa) {
            Presentation.SerKhoa.AddKhoaRequest inValue = new Presentation.SerKhoa.AddKhoaRequest();
            inValue.Body = new Presentation.SerKhoa.AddKhoaRequestBody();
            inValue.Body.khoa = khoa;
            return ((Presentation.SerKhoa.SerKhoaSoap)(this)).AddKhoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerKhoa.EditKhoaResponse Presentation.SerKhoa.SerKhoaSoap.EditKhoa(Presentation.SerKhoa.EditKhoaRequest request) {
            return base.Channel.EditKhoa(request);
        }
        
        public int EditKhoa(Presentation.SerKhoa.DTKhoa khoa) {
            Presentation.SerKhoa.EditKhoaRequest inValue = new Presentation.SerKhoa.EditKhoaRequest();
            inValue.Body = new Presentation.SerKhoa.EditKhoaRequestBody();
            inValue.Body.khoa = khoa;
            Presentation.SerKhoa.EditKhoaResponse retVal = ((Presentation.SerKhoa.SerKhoaSoap)(this)).EditKhoa(inValue);
            return retVal.Body.EditKhoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerKhoa.EditKhoaResponse> Presentation.SerKhoa.SerKhoaSoap.EditKhoaAsync(Presentation.SerKhoa.EditKhoaRequest request) {
            return base.Channel.EditKhoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerKhoa.EditKhoaResponse> EditKhoaAsync(Presentation.SerKhoa.DTKhoa khoa) {
            Presentation.SerKhoa.EditKhoaRequest inValue = new Presentation.SerKhoa.EditKhoaRequest();
            inValue.Body = new Presentation.SerKhoa.EditKhoaRequestBody();
            inValue.Body.khoa = khoa;
            return ((Presentation.SerKhoa.SerKhoaSoap)(this)).EditKhoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerKhoa.DeleteKhoaResponse Presentation.SerKhoa.SerKhoaSoap.DeleteKhoa(Presentation.SerKhoa.DeleteKhoaRequest request) {
            return base.Channel.DeleteKhoa(request);
        }
        
        public int DeleteKhoa(string ma) {
            Presentation.SerKhoa.DeleteKhoaRequest inValue = new Presentation.SerKhoa.DeleteKhoaRequest();
            inValue.Body = new Presentation.SerKhoa.DeleteKhoaRequestBody();
            inValue.Body.ma = ma;
            Presentation.SerKhoa.DeleteKhoaResponse retVal = ((Presentation.SerKhoa.SerKhoaSoap)(this)).DeleteKhoa(inValue);
            return retVal.Body.DeleteKhoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerKhoa.DeleteKhoaResponse> Presentation.SerKhoa.SerKhoaSoap.DeleteKhoaAsync(Presentation.SerKhoa.DeleteKhoaRequest request) {
            return base.Channel.DeleteKhoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerKhoa.DeleteKhoaResponse> DeleteKhoaAsync(string ma) {
            Presentation.SerKhoa.DeleteKhoaRequest inValue = new Presentation.SerKhoa.DeleteKhoaRequest();
            inValue.Body = new Presentation.SerKhoa.DeleteKhoaRequestBody();
            inValue.Body.ma = ma;
            return ((Presentation.SerKhoa.SerKhoaSoap)(this)).DeleteKhoaAsync(inValue);
        }
    }
}
