//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.SerDiem {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTDiem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTDiem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLopHocPhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLopHocPhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSinhVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSinhVienField;
        
        private double DiemChuyenCanField;
        
        private double DiemGiuaKyField;
        
        private double DiemThiField;
        
        private double DiemTrungBinhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaLopHocPhan {
            get {
                return this.MaLopHocPhanField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLopHocPhanField, value) != true)) {
                    this.MaLopHocPhanField = value;
                    this.RaisePropertyChanged("MaLopHocPhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenLopHocPhan {
            get {
                return this.TenLopHocPhanField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLopHocPhanField, value) != true)) {
                    this.TenLopHocPhanField = value;
                    this.RaisePropertyChanged("TenLopHocPhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MaSinhVien {
            get {
                return this.MaSinhVienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSinhVienField, value) != true)) {
                    this.MaSinhVienField = value;
                    this.RaisePropertyChanged("MaSinhVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TenSinhVien {
            get {
                return this.TenSinhVienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSinhVienField, value) != true)) {
                    this.TenSinhVienField = value;
                    this.RaisePropertyChanged("TenSinhVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double DiemChuyenCan {
            get {
                return this.DiemChuyenCanField;
            }
            set {
                if ((this.DiemChuyenCanField.Equals(value) != true)) {
                    this.DiemChuyenCanField = value;
                    this.RaisePropertyChanged("DiemChuyenCan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double DiemGiuaKy {
            get {
                return this.DiemGiuaKyField;
            }
            set {
                if ((this.DiemGiuaKyField.Equals(value) != true)) {
                    this.DiemGiuaKyField = value;
                    this.RaisePropertyChanged("DiemGiuaKy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double DiemThi {
            get {
                return this.DiemThiField;
            }
            set {
                if ((this.DiemThiField.Equals(value) != true)) {
                    this.DiemThiField = value;
                    this.RaisePropertyChanged("DiemThi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double DiemTrungBinh {
            get {
                return this.DiemTrungBinhField;
            }
            set {
                if ((this.DiemTrungBinhField.Equals(value) != true)) {
                    this.DiemTrungBinhField = value;
                    this.RaisePropertyChanged("DiemTrungBinh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTLophocphan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTLophocphan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLopHocPhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaMonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenMonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaGiangVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenGiangVienField;
        
        private byte HocKyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamHocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaLopHocPhan {
            get {
                return this.MaLopHocPhanField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLopHocPhanField, value) != true)) {
                    this.MaLopHocPhanField = value;
                    this.RaisePropertyChanged("MaLopHocPhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaMon {
            get {
                return this.MaMonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaMonField, value) != true)) {
                    this.MaMonField = value;
                    this.RaisePropertyChanged("MaMon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenMon {
            get {
                return this.TenMonField;
            }
            set {
                if ((object.ReferenceEquals(this.TenMonField, value) != true)) {
                    this.TenMonField = value;
                    this.RaisePropertyChanged("TenMon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MaGiangVien {
            get {
                return this.MaGiangVienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaGiangVienField, value) != true)) {
                    this.MaGiangVienField = value;
                    this.RaisePropertyChanged("MaGiangVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TenGiangVien {
            get {
                return this.TenGiangVienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenGiangVienField, value) != true)) {
                    this.TenGiangVienField = value;
                    this.RaisePropertyChanged("TenGiangVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public byte HocKy {
            get {
                return this.HocKyField;
            }
            set {
                if ((this.HocKyField.Equals(value) != true)) {
                    this.HocKyField = value;
                    this.RaisePropertyChanged("HocKy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NamHoc {
            get {
                return this.NamHocField;
            }
            set {
                if ((object.ReferenceEquals(this.NamHocField, value) != true)) {
                    this.NamHocField = value;
                    this.RaisePropertyChanged("NamHoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTSinhvien", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTSinhvien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSinhVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSinhVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoDemField;
        
        private bool GioiTinhField;
        
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLopHanhChinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLopHanhChinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AnhDaiDienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaSinhVien {
            get {
                return this.MaSinhVienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSinhVienField, value) != true)) {
                    this.MaSinhVienField = value;
                    this.RaisePropertyChanged("MaSinhVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenSinhVien {
            get {
                return this.TenSinhVienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSinhVienField, value) != true)) {
                    this.TenSinhVienField = value;
                    this.RaisePropertyChanged("TenSinhVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HoDem {
            get {
                return this.HoDemField;
            }
            set {
                if ((object.ReferenceEquals(this.HoDemField, value) != true)) {
                    this.HoDemField = value;
                    this.RaisePropertyChanged("HoDem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((this.GioiTinhField.Equals(value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MaLopHanhChinh {
            get {
                return this.MaLopHanhChinhField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLopHanhChinhField, value) != true)) {
                    this.MaLopHanhChinhField = value;
                    this.RaisePropertyChanged("MaLopHanhChinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TenLopHanhChinh {
            get {
                return this.TenLopHanhChinhField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLopHanhChinhField, value) != true)) {
                    this.TenLopHanhChinhField = value;
                    this.RaisePropertyChanged("TenLopHanhChinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] AnhDaiDien {
            get {
                return this.AnhDaiDienField;
            }
            set {
                if ((object.ReferenceEquals(this.AnhDaiDienField, value) != true)) {
                    this.AnhDaiDienField = value;
                    this.RaisePropertyChanged("AnhDaiDien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SerDiem.SerDiemSoap")]
    public interface SerDiemSoap {
        
        // CODEGEN: Generating message contract since element name GetAllDiemResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDiem", ReplyAction="*")]
        Presentation.SerDiem.GetAllDiemResponse GetAllDiem(Presentation.SerDiem.GetAllDiemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDiem", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerDiem.GetAllDiemResponse> GetAllDiemAsync(Presentation.SerDiem.GetAllDiemRequest request);
        
        // CODEGEN: Generating message contract since element name mal from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDiemByGV", ReplyAction="*")]
        Presentation.SerDiem.GetAllDiemByGVResponse GetAllDiemByGV(Presentation.SerDiem.GetAllDiemByGVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDiemByGV", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerDiem.GetAllDiemByGVResponse> GetAllDiemByGVAsync(Presentation.SerDiem.GetAllDiemByGVRequest request);
        
        // CODEGEN: Generating message contract since element name GetLopHPResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLopHP", ReplyAction="*")]
        Presentation.SerDiem.GetLopHPResponse GetLopHP(Presentation.SerDiem.GetLopHPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLopHP", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerDiem.GetLopHPResponse> GetLopHPAsync(Presentation.SerDiem.GetLopHPRequest request);
        
        // CODEGEN: Generating message contract since element name magv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSinhViens", ReplyAction="*")]
        Presentation.SerDiem.GetSinhViensResponse GetSinhViens(Presentation.SerDiem.GetSinhViensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSinhViens", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerDiem.GetSinhViensResponse> GetSinhViensAsync(Presentation.SerDiem.GetSinhViensRequest request);
        
        // CODEGEN: Generating message contract since element name diem from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDiem", ReplyAction="*")]
        Presentation.SerDiem.AddDiemResponse AddDiem(Presentation.SerDiem.AddDiemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDiem", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerDiem.AddDiemResponse> AddDiemAsync(Presentation.SerDiem.AddDiemRequest request);
        
        // CODEGEN: Generating message contract since element name diem from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditDiem", ReplyAction="*")]
        Presentation.SerDiem.EditDiemResponse EditDiem(Presentation.SerDiem.EditDiemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditDiem", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerDiem.EditDiemResponse> EditDiemAsync(Presentation.SerDiem.EditDiemRequest request);
        
        // CODEGEN: Generating message contract since element name diem from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDiem", ReplyAction="*")]
        Presentation.SerDiem.DeleteDiemResponse DeleteDiem(Presentation.SerDiem.DeleteDiemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDiem", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerDiem.DeleteDiemResponse> DeleteDiemAsync(Presentation.SerDiem.DeleteDiemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDiemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDiem", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.GetAllDiemRequestBody Body;
        
        public GetAllDiemRequest() {
        }
        
        public GetAllDiemRequest(Presentation.SerDiem.GetAllDiemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDiemRequestBody {
        
        public GetAllDiemRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDiemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDiemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.GetAllDiemResponseBody Body;
        
        public GetAllDiemResponse() {
        }
        
        public GetAllDiemResponse(Presentation.SerDiem.GetAllDiemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDiemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerDiem.DTDiem[] GetAllDiemResult;
        
        public GetAllDiemResponseBody() {
        }
        
        public GetAllDiemResponseBody(Presentation.SerDiem.DTDiem[] GetAllDiemResult) {
            this.GetAllDiemResult = GetAllDiemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDiemByGVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDiemByGV", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.GetAllDiemByGVRequestBody Body;
        
        public GetAllDiemByGVRequest() {
        }
        
        public GetAllDiemByGVRequest(Presentation.SerDiem.GetAllDiemByGVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDiemByGVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mal;
        
        public GetAllDiemByGVRequestBody() {
        }
        
        public GetAllDiemByGVRequestBody(string mal) {
            this.mal = mal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDiemByGVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDiemByGVResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.GetAllDiemByGVResponseBody Body;
        
        public GetAllDiemByGVResponse() {
        }
        
        public GetAllDiemByGVResponse(Presentation.SerDiem.GetAllDiemByGVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDiemByGVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerDiem.DTDiem[] GetAllDiemByGVResult;
        
        public GetAllDiemByGVResponseBody() {
        }
        
        public GetAllDiemByGVResponseBody(Presentation.SerDiem.DTDiem[] GetAllDiemByGVResult) {
            this.GetAllDiemByGVResult = GetAllDiemByGVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLopHPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLopHP", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.GetLopHPRequestBody Body;
        
        public GetLopHPRequest() {
        }
        
        public GetLopHPRequest(Presentation.SerDiem.GetLopHPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLopHPRequestBody {
        
        public GetLopHPRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLopHPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLopHPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.GetLopHPResponseBody Body;
        
        public GetLopHPResponse() {
        }
        
        public GetLopHPResponse(Presentation.SerDiem.GetLopHPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLopHPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerDiem.DTLophocphan[] GetLopHPResult;
        
        public GetLopHPResponseBody() {
        }
        
        public GetLopHPResponseBody(Presentation.SerDiem.DTLophocphan[] GetLopHPResult) {
            this.GetLopHPResult = GetLopHPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSinhViensRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSinhViens", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.GetSinhViensRequestBody Body;
        
        public GetSinhViensRequest() {
        }
        
        public GetSinhViensRequest(Presentation.SerDiem.GetSinhViensRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSinhViensRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string magv;
        
        public GetSinhViensRequestBody() {
        }
        
        public GetSinhViensRequestBody(string magv) {
            this.magv = magv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSinhViensResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSinhViensResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.GetSinhViensResponseBody Body;
        
        public GetSinhViensResponse() {
        }
        
        public GetSinhViensResponse(Presentation.SerDiem.GetSinhViensResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSinhViensResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerDiem.DTSinhvien[] GetSinhViensResult;
        
        public GetSinhViensResponseBody() {
        }
        
        public GetSinhViensResponseBody(Presentation.SerDiem.DTSinhvien[] GetSinhViensResult) {
            this.GetSinhViensResult = GetSinhViensResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDiemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDiem", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.AddDiemRequestBody Body;
        
        public AddDiemRequest() {
        }
        
        public AddDiemRequest(Presentation.SerDiem.AddDiemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDiemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerDiem.DTDiem diem;
        
        public AddDiemRequestBody() {
        }
        
        public AddDiemRequestBody(Presentation.SerDiem.DTDiem diem) {
            this.diem = diem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDiemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDiemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.AddDiemResponseBody Body;
        
        public AddDiemResponse() {
        }
        
        public AddDiemResponse(Presentation.SerDiem.AddDiemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDiemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddDiemResult;
        
        public AddDiemResponseBody() {
        }
        
        public AddDiemResponseBody(int AddDiemResult) {
            this.AddDiemResult = AddDiemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditDiemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditDiem", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.EditDiemRequestBody Body;
        
        public EditDiemRequest() {
        }
        
        public EditDiemRequest(Presentation.SerDiem.EditDiemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditDiemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerDiem.DTDiem diem;
        
        public EditDiemRequestBody() {
        }
        
        public EditDiemRequestBody(Presentation.SerDiem.DTDiem diem) {
            this.diem = diem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditDiemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditDiemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.EditDiemResponseBody Body;
        
        public EditDiemResponse() {
        }
        
        public EditDiemResponse(Presentation.SerDiem.EditDiemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditDiemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditDiemResult;
        
        public EditDiemResponseBody() {
        }
        
        public EditDiemResponseBody(bool EditDiemResult) {
            this.EditDiemResult = EditDiemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDiemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDiem", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.DeleteDiemRequestBody Body;
        
        public DeleteDiemRequest() {
        }
        
        public DeleteDiemRequest(Presentation.SerDiem.DeleteDiemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDiemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerDiem.DTDiem diem;
        
        public DeleteDiemRequestBody() {
        }
        
        public DeleteDiemRequestBody(Presentation.SerDiem.DTDiem diem) {
            this.diem = diem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDiemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDiemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerDiem.DeleteDiemResponseBody Body;
        
        public DeleteDiemResponse() {
        }
        
        public DeleteDiemResponse(Presentation.SerDiem.DeleteDiemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDiemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteDiemResult;
        
        public DeleteDiemResponseBody() {
        }
        
        public DeleteDiemResponseBody(bool DeleteDiemResult) {
            this.DeleteDiemResult = DeleteDiemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SerDiemSoapChannel : Presentation.SerDiem.SerDiemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerDiemSoapClient : System.ServiceModel.ClientBase<Presentation.SerDiem.SerDiemSoap>, Presentation.SerDiem.SerDiemSoap {
        
        public SerDiemSoapClient() {
        }
        
        public SerDiemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerDiemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerDiemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerDiemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerDiem.GetAllDiemResponse Presentation.SerDiem.SerDiemSoap.GetAllDiem(Presentation.SerDiem.GetAllDiemRequest request) {
            return base.Channel.GetAllDiem(request);
        }
        
        public Presentation.SerDiem.DTDiem[] GetAllDiem() {
            Presentation.SerDiem.GetAllDiemRequest inValue = new Presentation.SerDiem.GetAllDiemRequest();
            inValue.Body = new Presentation.SerDiem.GetAllDiemRequestBody();
            Presentation.SerDiem.GetAllDiemResponse retVal = ((Presentation.SerDiem.SerDiemSoap)(this)).GetAllDiem(inValue);
            return retVal.Body.GetAllDiemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerDiem.GetAllDiemResponse> Presentation.SerDiem.SerDiemSoap.GetAllDiemAsync(Presentation.SerDiem.GetAllDiemRequest request) {
            return base.Channel.GetAllDiemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerDiem.GetAllDiemResponse> GetAllDiemAsync() {
            Presentation.SerDiem.GetAllDiemRequest inValue = new Presentation.SerDiem.GetAllDiemRequest();
            inValue.Body = new Presentation.SerDiem.GetAllDiemRequestBody();
            return ((Presentation.SerDiem.SerDiemSoap)(this)).GetAllDiemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerDiem.GetAllDiemByGVResponse Presentation.SerDiem.SerDiemSoap.GetAllDiemByGV(Presentation.SerDiem.GetAllDiemByGVRequest request) {
            return base.Channel.GetAllDiemByGV(request);
        }
        
        public Presentation.SerDiem.DTDiem[] GetAllDiemByGV(string mal) {
            Presentation.SerDiem.GetAllDiemByGVRequest inValue = new Presentation.SerDiem.GetAllDiemByGVRequest();
            inValue.Body = new Presentation.SerDiem.GetAllDiemByGVRequestBody();
            inValue.Body.mal = mal;
            Presentation.SerDiem.GetAllDiemByGVResponse retVal = ((Presentation.SerDiem.SerDiemSoap)(this)).GetAllDiemByGV(inValue);
            return retVal.Body.GetAllDiemByGVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerDiem.GetAllDiemByGVResponse> Presentation.SerDiem.SerDiemSoap.GetAllDiemByGVAsync(Presentation.SerDiem.GetAllDiemByGVRequest request) {
            return base.Channel.GetAllDiemByGVAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerDiem.GetAllDiemByGVResponse> GetAllDiemByGVAsync(string mal) {
            Presentation.SerDiem.GetAllDiemByGVRequest inValue = new Presentation.SerDiem.GetAllDiemByGVRequest();
            inValue.Body = new Presentation.SerDiem.GetAllDiemByGVRequestBody();
            inValue.Body.mal = mal;
            return ((Presentation.SerDiem.SerDiemSoap)(this)).GetAllDiemByGVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerDiem.GetLopHPResponse Presentation.SerDiem.SerDiemSoap.GetLopHP(Presentation.SerDiem.GetLopHPRequest request) {
            return base.Channel.GetLopHP(request);
        }
        
        public Presentation.SerDiem.DTLophocphan[] GetLopHP() {
            Presentation.SerDiem.GetLopHPRequest inValue = new Presentation.SerDiem.GetLopHPRequest();
            inValue.Body = new Presentation.SerDiem.GetLopHPRequestBody();
            Presentation.SerDiem.GetLopHPResponse retVal = ((Presentation.SerDiem.SerDiemSoap)(this)).GetLopHP(inValue);
            return retVal.Body.GetLopHPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerDiem.GetLopHPResponse> Presentation.SerDiem.SerDiemSoap.GetLopHPAsync(Presentation.SerDiem.GetLopHPRequest request) {
            return base.Channel.GetLopHPAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerDiem.GetLopHPResponse> GetLopHPAsync() {
            Presentation.SerDiem.GetLopHPRequest inValue = new Presentation.SerDiem.GetLopHPRequest();
            inValue.Body = new Presentation.SerDiem.GetLopHPRequestBody();
            return ((Presentation.SerDiem.SerDiemSoap)(this)).GetLopHPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerDiem.GetSinhViensResponse Presentation.SerDiem.SerDiemSoap.GetSinhViens(Presentation.SerDiem.GetSinhViensRequest request) {
            return base.Channel.GetSinhViens(request);
        }
        
        public Presentation.SerDiem.DTSinhvien[] GetSinhViens(string magv) {
            Presentation.SerDiem.GetSinhViensRequest inValue = new Presentation.SerDiem.GetSinhViensRequest();
            inValue.Body = new Presentation.SerDiem.GetSinhViensRequestBody();
            inValue.Body.magv = magv;
            Presentation.SerDiem.GetSinhViensResponse retVal = ((Presentation.SerDiem.SerDiemSoap)(this)).GetSinhViens(inValue);
            return retVal.Body.GetSinhViensResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerDiem.GetSinhViensResponse> Presentation.SerDiem.SerDiemSoap.GetSinhViensAsync(Presentation.SerDiem.GetSinhViensRequest request) {
            return base.Channel.GetSinhViensAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerDiem.GetSinhViensResponse> GetSinhViensAsync(string magv) {
            Presentation.SerDiem.GetSinhViensRequest inValue = new Presentation.SerDiem.GetSinhViensRequest();
            inValue.Body = new Presentation.SerDiem.GetSinhViensRequestBody();
            inValue.Body.magv = magv;
            return ((Presentation.SerDiem.SerDiemSoap)(this)).GetSinhViensAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerDiem.AddDiemResponse Presentation.SerDiem.SerDiemSoap.AddDiem(Presentation.SerDiem.AddDiemRequest request) {
            return base.Channel.AddDiem(request);
        }
        
        public int AddDiem(Presentation.SerDiem.DTDiem diem) {
            Presentation.SerDiem.AddDiemRequest inValue = new Presentation.SerDiem.AddDiemRequest();
            inValue.Body = new Presentation.SerDiem.AddDiemRequestBody();
            inValue.Body.diem = diem;
            Presentation.SerDiem.AddDiemResponse retVal = ((Presentation.SerDiem.SerDiemSoap)(this)).AddDiem(inValue);
            return retVal.Body.AddDiemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerDiem.AddDiemResponse> Presentation.SerDiem.SerDiemSoap.AddDiemAsync(Presentation.SerDiem.AddDiemRequest request) {
            return base.Channel.AddDiemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerDiem.AddDiemResponse> AddDiemAsync(Presentation.SerDiem.DTDiem diem) {
            Presentation.SerDiem.AddDiemRequest inValue = new Presentation.SerDiem.AddDiemRequest();
            inValue.Body = new Presentation.SerDiem.AddDiemRequestBody();
            inValue.Body.diem = diem;
            return ((Presentation.SerDiem.SerDiemSoap)(this)).AddDiemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerDiem.EditDiemResponse Presentation.SerDiem.SerDiemSoap.EditDiem(Presentation.SerDiem.EditDiemRequest request) {
            return base.Channel.EditDiem(request);
        }
        
        public bool EditDiem(Presentation.SerDiem.DTDiem diem) {
            Presentation.SerDiem.EditDiemRequest inValue = new Presentation.SerDiem.EditDiemRequest();
            inValue.Body = new Presentation.SerDiem.EditDiemRequestBody();
            inValue.Body.diem = diem;
            Presentation.SerDiem.EditDiemResponse retVal = ((Presentation.SerDiem.SerDiemSoap)(this)).EditDiem(inValue);
            return retVal.Body.EditDiemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerDiem.EditDiemResponse> Presentation.SerDiem.SerDiemSoap.EditDiemAsync(Presentation.SerDiem.EditDiemRequest request) {
            return base.Channel.EditDiemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerDiem.EditDiemResponse> EditDiemAsync(Presentation.SerDiem.DTDiem diem) {
            Presentation.SerDiem.EditDiemRequest inValue = new Presentation.SerDiem.EditDiemRequest();
            inValue.Body = new Presentation.SerDiem.EditDiemRequestBody();
            inValue.Body.diem = diem;
            return ((Presentation.SerDiem.SerDiemSoap)(this)).EditDiemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerDiem.DeleteDiemResponse Presentation.SerDiem.SerDiemSoap.DeleteDiem(Presentation.SerDiem.DeleteDiemRequest request) {
            return base.Channel.DeleteDiem(request);
        }
        
        public bool DeleteDiem(Presentation.SerDiem.DTDiem diem) {
            Presentation.SerDiem.DeleteDiemRequest inValue = new Presentation.SerDiem.DeleteDiemRequest();
            inValue.Body = new Presentation.SerDiem.DeleteDiemRequestBody();
            inValue.Body.diem = diem;
            Presentation.SerDiem.DeleteDiemResponse retVal = ((Presentation.SerDiem.SerDiemSoap)(this)).DeleteDiem(inValue);
            return retVal.Body.DeleteDiemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerDiem.DeleteDiemResponse> Presentation.SerDiem.SerDiemSoap.DeleteDiemAsync(Presentation.SerDiem.DeleteDiemRequest request) {
            return base.Channel.DeleteDiemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerDiem.DeleteDiemResponse> DeleteDiemAsync(Presentation.SerDiem.DTDiem diem) {
            Presentation.SerDiem.DeleteDiemRequest inValue = new Presentation.SerDiem.DeleteDiemRequest();
            inValue.Body = new Presentation.SerDiem.DeleteDiemRequestBody();
            inValue.Body.diem = diem;
            return ((Presentation.SerDiem.SerDiemSoap)(this)).DeleteDiemAsync(inValue);
        }
    }
}
