//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.SerGiangvien {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTGiangvien", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTGiangvien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaGiangVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenGiangVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoDemField;
        
        private bool GioiTinhField;
        
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HocViField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaGiangVien {
            get {
                return this.MaGiangVienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaGiangVienField, value) != true)) {
                    this.MaGiangVienField = value;
                    this.RaisePropertyChanged("MaGiangVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenGiangVien {
            get {
                return this.TenGiangVienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenGiangVienField, value) != true)) {
                    this.TenGiangVienField = value;
                    this.RaisePropertyChanged("TenGiangVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HoDem {
            get {
                return this.HoDemField;
            }
            set {
                if ((object.ReferenceEquals(this.HoDemField, value) != true)) {
                    this.HoDemField = value;
                    this.RaisePropertyChanged("HoDem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((this.GioiTinhField.Equals(value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string HocVi {
            get {
                return this.HocViField;
            }
            set {
                if ((object.ReferenceEquals(this.HocViField, value) != true)) {
                    this.HocViField = value;
                    this.RaisePropertyChanged("HocVi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTKhoa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTKhoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDienThoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SoDienThoai {
            get {
                return this.SoDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDienThoaiField, value) != true)) {
                    this.SoDienThoaiField = value;
                    this.RaisePropertyChanged("SoDienThoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SerGiangvien.SerGiangvienSoap")]
    public interface SerGiangvienSoap {
        
        // CODEGEN: Generating message contract since element name GetAllGiangVienResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGiangVien", ReplyAction="*")]
        Presentation.SerGiangvien.GetAllGiangVienResponse GetAllGiangVien(Presentation.SerGiangvien.GetAllGiangVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGiangVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.GetAllGiangVienResponse> GetAllGiangVienAsync(Presentation.SerGiangvien.GetAllGiangVienRequest request);
        
        // CODEGEN: Generating message contract since element name GetKhoaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKhoa", ReplyAction="*")]
        Presentation.SerGiangvien.GetKhoaResponse GetKhoa(Presentation.SerGiangvien.GetKhoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKhoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.GetKhoaResponse> GetKhoaAsync(Presentation.SerGiangvien.GetKhoaRequest request);
        
        // CODEGEN: Generating message contract since element name GetTinhResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTinh", ReplyAction="*")]
        Presentation.SerGiangvien.GetTinhResponse GetTinh(Presentation.SerGiangvien.GetTinhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTinh", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.GetTinhResponse> GetTinhAsync(Presentation.SerGiangvien.GetTinhRequest request);
        
        // CODEGEN: Generating message contract since element name maT from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHuyen", ReplyAction="*")]
        Presentation.SerGiangvien.GetHuyenResponse GetHuyen(Presentation.SerGiangvien.GetHuyenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHuyen", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.GetHuyenResponse> GetHuyenAsync(Presentation.SerGiangvien.GetHuyenRequest request);
        
        // CODEGEN: Generating message contract since element name maH from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXa", ReplyAction="*")]
        Presentation.SerGiangvien.GetXaResponse GetXa(Presentation.SerGiangvien.GetXaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXa", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.GetXaResponse> GetXaAsync(Presentation.SerGiangvien.GetXaRequest request);
        
        // CODEGEN: Generating message contract since element name giangVien from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemGiangVien", ReplyAction="*")]
        Presentation.SerGiangvien.ThemGiangVienResponse ThemGiangVien(Presentation.SerGiangvien.ThemGiangVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemGiangVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.ThemGiangVienResponse> ThemGiangVienAsync(Presentation.SerGiangvien.ThemGiangVienRequest request);
        
        // CODEGEN: Generating message contract since element name giangVien from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditGiangVien", ReplyAction="*")]
        Presentation.SerGiangvien.EditGiangVienResponse EditGiangVien(Presentation.SerGiangvien.EditGiangVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditGiangVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.EditGiangVienResponse> EditGiangVienAsync(Presentation.SerGiangvien.EditGiangVienRequest request);
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteGiangVien", ReplyAction="*")]
        Presentation.SerGiangvien.DeleteGiangVienResponse DeleteGiangVien(Presentation.SerGiangvien.DeleteGiangVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteGiangVien", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.DeleteGiangVienResponse> DeleteGiangVienAsync(Presentation.SerGiangvien.DeleteGiangVienRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGiangVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGiangVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.GetAllGiangVienRequestBody Body;
        
        public GetAllGiangVienRequest() {
        }
        
        public GetAllGiangVienRequest(Presentation.SerGiangvien.GetAllGiangVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllGiangVienRequestBody {
        
        public GetAllGiangVienRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGiangVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGiangVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.GetAllGiangVienResponseBody Body;
        
        public GetAllGiangVienResponse() {
        }
        
        public GetAllGiangVienResponse(Presentation.SerGiangvien.GetAllGiangVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllGiangVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerGiangvien.DTGiangvien[] GetAllGiangVienResult;
        
        public GetAllGiangVienResponseBody() {
        }
        
        public GetAllGiangVienResponseBody(Presentation.SerGiangvien.DTGiangvien[] GetAllGiangVienResult) {
            this.GetAllGiangVienResult = GetAllGiangVienResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKhoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKhoa", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.GetKhoaRequestBody Body;
        
        public GetKhoaRequest() {
        }
        
        public GetKhoaRequest(Presentation.SerGiangvien.GetKhoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetKhoaRequestBody {
        
        public GetKhoaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKhoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKhoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.GetKhoaResponseBody Body;
        
        public GetKhoaResponse() {
        }
        
        public GetKhoaResponse(Presentation.SerGiangvien.GetKhoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKhoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerGiangvien.DTKhoa[] GetKhoaResult;
        
        public GetKhoaResponseBody() {
        }
        
        public GetKhoaResponseBody(Presentation.SerGiangvien.DTKhoa[] GetKhoaResult) {
            this.GetKhoaResult = GetKhoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTinhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTinh", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.GetTinhRequestBody Body;
        
        public GetTinhRequest() {
        }
        
        public GetTinhRequest(Presentation.SerGiangvien.GetTinhRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTinhRequestBody {
        
        public GetTinhRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTinhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTinhResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.GetTinhResponseBody Body;
        
        public GetTinhResponse() {
        }
        
        public GetTinhResponse(Presentation.SerGiangvien.GetTinhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTinhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerGiangvien.ArrayOfString[] GetTinhResult;
        
        public GetTinhResponseBody() {
        }
        
        public GetTinhResponseBody(Presentation.SerGiangvien.ArrayOfString[] GetTinhResult) {
            this.GetTinhResult = GetTinhResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHuyenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHuyen", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.GetHuyenRequestBody Body;
        
        public GetHuyenRequest() {
        }
        
        public GetHuyenRequest(Presentation.SerGiangvien.GetHuyenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHuyenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string maT;
        
        public GetHuyenRequestBody() {
        }
        
        public GetHuyenRequestBody(string maT) {
            this.maT = maT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHuyenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHuyenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.GetHuyenResponseBody Body;
        
        public GetHuyenResponse() {
        }
        
        public GetHuyenResponse(Presentation.SerGiangvien.GetHuyenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHuyenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerGiangvien.ArrayOfString[] GetHuyenResult;
        
        public GetHuyenResponseBody() {
        }
        
        public GetHuyenResponseBody(Presentation.SerGiangvien.ArrayOfString[] GetHuyenResult) {
            this.GetHuyenResult = GetHuyenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXa", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.GetXaRequestBody Body;
        
        public GetXaRequest() {
        }
        
        public GetXaRequest(Presentation.SerGiangvien.GetXaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string maH;
        
        public GetXaRequestBody() {
        }
        
        public GetXaRequestBody(string maH) {
            this.maH = maH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.GetXaResponseBody Body;
        
        public GetXaResponse() {
        }
        
        public GetXaResponse(Presentation.SerGiangvien.GetXaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerGiangvien.ArrayOfString[] GetXaResult;
        
        public GetXaResponseBody() {
        }
        
        public GetXaResponseBody(Presentation.SerGiangvien.ArrayOfString[] GetXaResult) {
            this.GetXaResult = GetXaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ThemGiangVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ThemGiangVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.ThemGiangVienRequestBody Body;
        
        public ThemGiangVienRequest() {
        }
        
        public ThemGiangVienRequest(Presentation.SerGiangvien.ThemGiangVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ThemGiangVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerGiangvien.DTGiangvien giangVien;
        
        public ThemGiangVienRequestBody() {
        }
        
        public ThemGiangVienRequestBody(Presentation.SerGiangvien.DTGiangvien giangVien) {
            this.giangVien = giangVien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ThemGiangVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ThemGiangVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.ThemGiangVienResponseBody Body;
        
        public ThemGiangVienResponse() {
        }
        
        public ThemGiangVienResponse(Presentation.SerGiangvien.ThemGiangVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ThemGiangVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ThemGiangVienResult;
        
        public ThemGiangVienResponseBody() {
        }
        
        public ThemGiangVienResponseBody(bool ThemGiangVienResult) {
            this.ThemGiangVienResult = ThemGiangVienResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditGiangVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditGiangVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.EditGiangVienRequestBody Body;
        
        public EditGiangVienRequest() {
        }
        
        public EditGiangVienRequest(Presentation.SerGiangvien.EditGiangVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditGiangVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentation.SerGiangvien.DTGiangvien giangVien;
        
        public EditGiangVienRequestBody() {
        }
        
        public EditGiangVienRequestBody(Presentation.SerGiangvien.DTGiangvien giangVien) {
            this.giangVien = giangVien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditGiangVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditGiangVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.EditGiangVienResponseBody Body;
        
        public EditGiangVienResponse() {
        }
        
        public EditGiangVienResponse(Presentation.SerGiangvien.EditGiangVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditGiangVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditGiangVienResult;
        
        public EditGiangVienResponseBody() {
        }
        
        public EditGiangVienResponseBody(bool EditGiangVienResult) {
            this.EditGiangVienResult = EditGiangVienResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteGiangVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteGiangVien", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.DeleteGiangVienRequestBody Body;
        
        public DeleteGiangVienRequest() {
        }
        
        public DeleteGiangVienRequest(Presentation.SerGiangvien.DeleteGiangVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteGiangVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        public DeleteGiangVienRequestBody() {
        }
        
        public DeleteGiangVienRequestBody(string ma) {
            this.ma = ma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteGiangVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteGiangVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public Presentation.SerGiangvien.DeleteGiangVienResponseBody Body;
        
        public DeleteGiangVienResponse() {
        }
        
        public DeleteGiangVienResponse(Presentation.SerGiangvien.DeleteGiangVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteGiangVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteGiangVienResult;
        
        public DeleteGiangVienResponseBody() {
        }
        
        public DeleteGiangVienResponseBody(bool DeleteGiangVienResult) {
            this.DeleteGiangVienResult = DeleteGiangVienResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SerGiangvienSoapChannel : Presentation.SerGiangvien.SerGiangvienSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerGiangvienSoapClient : System.ServiceModel.ClientBase<Presentation.SerGiangvien.SerGiangvienSoap>, Presentation.SerGiangvien.SerGiangvienSoap {
        
        public SerGiangvienSoapClient() {
        }
        
        public SerGiangvienSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerGiangvienSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerGiangvienSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerGiangvienSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerGiangvien.GetAllGiangVienResponse Presentation.SerGiangvien.SerGiangvienSoap.GetAllGiangVien(Presentation.SerGiangvien.GetAllGiangVienRequest request) {
            return base.Channel.GetAllGiangVien(request);
        }
        
        public Presentation.SerGiangvien.DTGiangvien[] GetAllGiangVien() {
            Presentation.SerGiangvien.GetAllGiangVienRequest inValue = new Presentation.SerGiangvien.GetAllGiangVienRequest();
            inValue.Body = new Presentation.SerGiangvien.GetAllGiangVienRequestBody();
            Presentation.SerGiangvien.GetAllGiangVienResponse retVal = ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).GetAllGiangVien(inValue);
            return retVal.Body.GetAllGiangVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.GetAllGiangVienResponse> Presentation.SerGiangvien.SerGiangvienSoap.GetAllGiangVienAsync(Presentation.SerGiangvien.GetAllGiangVienRequest request) {
            return base.Channel.GetAllGiangVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerGiangvien.GetAllGiangVienResponse> GetAllGiangVienAsync() {
            Presentation.SerGiangvien.GetAllGiangVienRequest inValue = new Presentation.SerGiangvien.GetAllGiangVienRequest();
            inValue.Body = new Presentation.SerGiangvien.GetAllGiangVienRequestBody();
            return ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).GetAllGiangVienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerGiangvien.GetKhoaResponse Presentation.SerGiangvien.SerGiangvienSoap.GetKhoa(Presentation.SerGiangvien.GetKhoaRequest request) {
            return base.Channel.GetKhoa(request);
        }
        
        public Presentation.SerGiangvien.DTKhoa[] GetKhoa() {
            Presentation.SerGiangvien.GetKhoaRequest inValue = new Presentation.SerGiangvien.GetKhoaRequest();
            inValue.Body = new Presentation.SerGiangvien.GetKhoaRequestBody();
            Presentation.SerGiangvien.GetKhoaResponse retVal = ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).GetKhoa(inValue);
            return retVal.Body.GetKhoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.GetKhoaResponse> Presentation.SerGiangvien.SerGiangvienSoap.GetKhoaAsync(Presentation.SerGiangvien.GetKhoaRequest request) {
            return base.Channel.GetKhoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerGiangvien.GetKhoaResponse> GetKhoaAsync() {
            Presentation.SerGiangvien.GetKhoaRequest inValue = new Presentation.SerGiangvien.GetKhoaRequest();
            inValue.Body = new Presentation.SerGiangvien.GetKhoaRequestBody();
            return ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).GetKhoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerGiangvien.GetTinhResponse Presentation.SerGiangvien.SerGiangvienSoap.GetTinh(Presentation.SerGiangvien.GetTinhRequest request) {
            return base.Channel.GetTinh(request);
        }
        
        public Presentation.SerGiangvien.ArrayOfString[] GetTinh() {
            Presentation.SerGiangvien.GetTinhRequest inValue = new Presentation.SerGiangvien.GetTinhRequest();
            inValue.Body = new Presentation.SerGiangvien.GetTinhRequestBody();
            Presentation.SerGiangvien.GetTinhResponse retVal = ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).GetTinh(inValue);
            return retVal.Body.GetTinhResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.GetTinhResponse> Presentation.SerGiangvien.SerGiangvienSoap.GetTinhAsync(Presentation.SerGiangvien.GetTinhRequest request) {
            return base.Channel.GetTinhAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerGiangvien.GetTinhResponse> GetTinhAsync() {
            Presentation.SerGiangvien.GetTinhRequest inValue = new Presentation.SerGiangvien.GetTinhRequest();
            inValue.Body = new Presentation.SerGiangvien.GetTinhRequestBody();
            return ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).GetTinhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerGiangvien.GetHuyenResponse Presentation.SerGiangvien.SerGiangvienSoap.GetHuyen(Presentation.SerGiangvien.GetHuyenRequest request) {
            return base.Channel.GetHuyen(request);
        }
        
        public Presentation.SerGiangvien.ArrayOfString[] GetHuyen(string maT) {
            Presentation.SerGiangvien.GetHuyenRequest inValue = new Presentation.SerGiangvien.GetHuyenRequest();
            inValue.Body = new Presentation.SerGiangvien.GetHuyenRequestBody();
            inValue.Body.maT = maT;
            Presentation.SerGiangvien.GetHuyenResponse retVal = ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).GetHuyen(inValue);
            return retVal.Body.GetHuyenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.GetHuyenResponse> Presentation.SerGiangvien.SerGiangvienSoap.GetHuyenAsync(Presentation.SerGiangvien.GetHuyenRequest request) {
            return base.Channel.GetHuyenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerGiangvien.GetHuyenResponse> GetHuyenAsync(string maT) {
            Presentation.SerGiangvien.GetHuyenRequest inValue = new Presentation.SerGiangvien.GetHuyenRequest();
            inValue.Body = new Presentation.SerGiangvien.GetHuyenRequestBody();
            inValue.Body.maT = maT;
            return ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).GetHuyenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerGiangvien.GetXaResponse Presentation.SerGiangvien.SerGiangvienSoap.GetXa(Presentation.SerGiangvien.GetXaRequest request) {
            return base.Channel.GetXa(request);
        }
        
        public Presentation.SerGiangvien.ArrayOfString[] GetXa(string maH) {
            Presentation.SerGiangvien.GetXaRequest inValue = new Presentation.SerGiangvien.GetXaRequest();
            inValue.Body = new Presentation.SerGiangvien.GetXaRequestBody();
            inValue.Body.maH = maH;
            Presentation.SerGiangvien.GetXaResponse retVal = ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).GetXa(inValue);
            return retVal.Body.GetXaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.GetXaResponse> Presentation.SerGiangvien.SerGiangvienSoap.GetXaAsync(Presentation.SerGiangvien.GetXaRequest request) {
            return base.Channel.GetXaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerGiangvien.GetXaResponse> GetXaAsync(string maH) {
            Presentation.SerGiangvien.GetXaRequest inValue = new Presentation.SerGiangvien.GetXaRequest();
            inValue.Body = new Presentation.SerGiangvien.GetXaRequestBody();
            inValue.Body.maH = maH;
            return ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).GetXaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerGiangvien.ThemGiangVienResponse Presentation.SerGiangvien.SerGiangvienSoap.ThemGiangVien(Presentation.SerGiangvien.ThemGiangVienRequest request) {
            return base.Channel.ThemGiangVien(request);
        }
        
        public bool ThemGiangVien(Presentation.SerGiangvien.DTGiangvien giangVien) {
            Presentation.SerGiangvien.ThemGiangVienRequest inValue = new Presentation.SerGiangvien.ThemGiangVienRequest();
            inValue.Body = new Presentation.SerGiangvien.ThemGiangVienRequestBody();
            inValue.Body.giangVien = giangVien;
            Presentation.SerGiangvien.ThemGiangVienResponse retVal = ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).ThemGiangVien(inValue);
            return retVal.Body.ThemGiangVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.ThemGiangVienResponse> Presentation.SerGiangvien.SerGiangvienSoap.ThemGiangVienAsync(Presentation.SerGiangvien.ThemGiangVienRequest request) {
            return base.Channel.ThemGiangVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerGiangvien.ThemGiangVienResponse> ThemGiangVienAsync(Presentation.SerGiangvien.DTGiangvien giangVien) {
            Presentation.SerGiangvien.ThemGiangVienRequest inValue = new Presentation.SerGiangvien.ThemGiangVienRequest();
            inValue.Body = new Presentation.SerGiangvien.ThemGiangVienRequestBody();
            inValue.Body.giangVien = giangVien;
            return ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).ThemGiangVienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerGiangvien.EditGiangVienResponse Presentation.SerGiangvien.SerGiangvienSoap.EditGiangVien(Presentation.SerGiangvien.EditGiangVienRequest request) {
            return base.Channel.EditGiangVien(request);
        }
        
        public bool EditGiangVien(Presentation.SerGiangvien.DTGiangvien giangVien) {
            Presentation.SerGiangvien.EditGiangVienRequest inValue = new Presentation.SerGiangvien.EditGiangVienRequest();
            inValue.Body = new Presentation.SerGiangvien.EditGiangVienRequestBody();
            inValue.Body.giangVien = giangVien;
            Presentation.SerGiangvien.EditGiangVienResponse retVal = ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).EditGiangVien(inValue);
            return retVal.Body.EditGiangVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.EditGiangVienResponse> Presentation.SerGiangvien.SerGiangvienSoap.EditGiangVienAsync(Presentation.SerGiangvien.EditGiangVienRequest request) {
            return base.Channel.EditGiangVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerGiangvien.EditGiangVienResponse> EditGiangVienAsync(Presentation.SerGiangvien.DTGiangvien giangVien) {
            Presentation.SerGiangvien.EditGiangVienRequest inValue = new Presentation.SerGiangvien.EditGiangVienRequest();
            inValue.Body = new Presentation.SerGiangvien.EditGiangVienRequestBody();
            inValue.Body.giangVien = giangVien;
            return ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).EditGiangVienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentation.SerGiangvien.DeleteGiangVienResponse Presentation.SerGiangvien.SerGiangvienSoap.DeleteGiangVien(Presentation.SerGiangvien.DeleteGiangVienRequest request) {
            return base.Channel.DeleteGiangVien(request);
        }
        
        public bool DeleteGiangVien(string ma) {
            Presentation.SerGiangvien.DeleteGiangVienRequest inValue = new Presentation.SerGiangvien.DeleteGiangVienRequest();
            inValue.Body = new Presentation.SerGiangvien.DeleteGiangVienRequestBody();
            inValue.Body.ma = ma;
            Presentation.SerGiangvien.DeleteGiangVienResponse retVal = ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).DeleteGiangVien(inValue);
            return retVal.Body.DeleteGiangVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentation.SerGiangvien.DeleteGiangVienResponse> Presentation.SerGiangvien.SerGiangvienSoap.DeleteGiangVienAsync(Presentation.SerGiangvien.DeleteGiangVienRequest request) {
            return base.Channel.DeleteGiangVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentation.SerGiangvien.DeleteGiangVienResponse> DeleteGiangVienAsync(string ma) {
            Presentation.SerGiangvien.DeleteGiangVienRequest inValue = new Presentation.SerGiangvien.DeleteGiangVienRequest();
            inValue.Body = new Presentation.SerGiangvien.DeleteGiangVienRequestBody();
            inValue.Body.ma = ma;
            return ((Presentation.SerGiangvien.SerGiangvienSoap)(this)).DeleteGiangVienAsync(inValue);
        }
    }
}
